parameters:
  - name: checkout
    type: string
    default: self
  - name: store
    type: boolean
    default: false

steps:
  - checkout: ${{ parameters.checkout }}
    displayName: "Checkout '${{ parameters.checkout }}'"

  - script: git fetch origin pull/$(PR)/head && git checkout FETCH_HEAD
    workingDirectory: $(Build.SourcesDirectory)
    condition: ne(variables['PR'], '')
    displayName: "Switch to PR $(PR)"

  - template: ../../utils/npm.yml
    parameters:
      directories:
        - $(Build.SourcesDirectory)
        - $(Build.SourcesDirectory)/packages/survey-creator-core
        - $(Build.SourcesDirectory)/packages/survey-creator-angular
        - $(Build.SourcesDirectory)/packages/survey-creator-angular/example/angular-ui

  - template: ../../utils/artifact.yml
    parameters:
      artifacts:
        - $(ArtifactNameLibraryCore)
        - $(ArtifactNameLibraryAngular)

  - template: ../../utils/copy.yml
    parameters:
      items:
        - source: $(Agent.TempDirectory)/$(ArtifactNameLibraryCore)
          destination: $(Build.SourcesDirectory)/packages/survey-creator-core/node_modules/survey-core
        - source: $(Agent.TempDirectory)/$(ArtifactNameLibraryCore)
          destination: $(Build.SourcesDirectory)/packages/survey-creator-angular/node_modules/survey-core
        - source: $(Agent.TempDirectory)/$(ArtifactNameLibraryAngular)
          destination: $(Build.SourcesDirectory)/packages/survey-creator-angular/node_modules/survey-angular-ui

  - script: npm run build:all
    workingDirectory: $(Build.SourcesDirectory)/packages/survey-creator-core
    displayName: "Build Core"

  - script: npm run build
    workingDirectory: $(Build.SourcesDirectory)/packages/survey-creator-angular
    displayName: "Build"

  - ${{ if eq(parameters.store, true) }}:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/packages/survey-creator-angular/build/'
        ArtifactName: $(ArtifactNameCreatorV2Angular) 
        publishLocation: 'Container'
        StoreAsTar: true