# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    exclude:
      - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: "Ubuntu-22.04"

jobs:
  - job: Core
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/"
          Contents: "package.json"
          TargetFolder: "$(Build.SourcesDirectory)/Temp/"
          OverWrite: true
        displayName: "Copy package.json for cache key"

      - task: Cache@2
        inputs:
          key: "npm-cache-library | $(Build.SourcesDirectory)/Temp/package.json"
          path: $(Build.SourcesDirectory)/node_modules
          cacheHitVar: NPM_CACHE_RESTORED
        displayName: Cache NPMs

      - task: Npm@1
        displayName: "NPM install root"
        inputs:
          command: install
          verbose: false
        condition: ne(variables.NPM_CACHE_RESTORED, 'true')

      - script: |
          npm run lint
        displayName: "run lint command"

      - script: |
          npx puppeteer browsers install chrome
        displayName: "install chrome"

      - script: |
          cd packages/survey-core
          npm install
        displayName: "NPM install packages/survey-core"

      - script: |
          cd packages/survey-core
          npm run build:all
        displayName: "Build core"

      - script: |
          cd packages/survey-core
          npm test
        displayName: "run unit test"

      - script: |
          cd packages/survey-core
          npm run test:postcss
        displayName: "check postcss compatibility"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/packages/survey-core/build"
          targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/build/survey-core

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/build/survey-core"
          ArtifactName: "SurveyJSLibraryBuildCore-$(Build.BuildId)"
          publishLocation: "Container"

  - job: React
    dependsOn: Core
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/"
          Contents: "package.json"
          TargetFolder: "$(Build.SourcesDirectory)/Temp/"
          OverWrite: true
        displayName: "Copy package.json for cache key"

      - task: Cache@2
        inputs:
          key: "npm-cache-library | $(Build.SourcesDirectory)/Temp/package.json"
          path: $(Build.SourcesDirectory)/node_modules
          cacheHitVar: NPM_CACHE_RESTORED
        displayName: Cache NPMs

      - task: Npm@1
        displayName: "NPM install root"
        inputs:
          command: install
          verbose: false
        condition: ne(variables.NPM_CACHE_RESTORED, 'true')

      - script: |
          npm run postinstall
        displayName: "install playwright chrome"

      - script: |
          npx puppeteer browsers install chrome
        displayName: "install chrome"

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: "current"
          downloadType: "single"
          artifactName: "SurveyJSLibraryBuildCore-$(Build.BuildId)"
          downloadPath: "$(System.ArtifactsDirectory)"

      - task: CopyFiles@2
        inputs:
          SourceFolder: $(System.ArtifactsDirectory)/SurveyJSLibraryBuildCore-$(Build.BuildId)
          TargetFolder: "$(Build.SourcesDirectory)/packages/survey-core/build"

      - script: |
          cd packages/survey-react-ui
          npm install
        displayName: "NPM install packages/survey-react-ui"

      - script: |
          cd packages/survey-react-ui
          npm run build
        displayName: "Build React"

      - script: |
          cd packages/survey-react-ui
          npm run test
        displayName: "run markup tests"

      - script: |
          cd packages/survey-react-ui
          npm run e2e:ci
        displayName: "run e2e tests"

      - bash: |
          cd packages/survey-react-ui
          npm run testcafe:ci
        displayName: "run functional tests"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/packages/survey-react-ui/test-results"
          Contents: "**"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/Library_React_E2E"
          OverWrite: true
        condition: always()
        displayName: "copy e2e artifacts"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/Library_React_E2E/"
          ArtifactName: "Library_React_E2E"
          publishLocation: "Container"
        condition: always()
        displayName: "publish e2e artifacts"

      - task: PublishTestResults@2
        displayName: "Publish test results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-react-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "React End-To-End Tests"
        condition: succeededOrFailed()

      # - task: PublishPipelineArtifact@1
      #   inputs:
      #     targetPath: "$(Build.SourcesDirectory)/packages/survey-react-ui/playwright-report"
      #     artifact: react-playwright-report
      #     publishLocation: "pipeline"
      #   condition: succeededOrFailed()

  - job: Angular
    dependsOn: Core
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/"
          Contents: "package.json"
          TargetFolder: "$(Build.SourcesDirectory)/Temp/"
          OverWrite: true
        displayName: "Copy package.json for cache key"

      - task: Cache@2
        inputs:
          key: "npm-cache-library | $(Build.SourcesDirectory)/Temp/package.json"
          path: $(Build.SourcesDirectory)/node_modules
          cacheHitVar: NPM_CACHE_RESTORED
        displayName: Cache NPMs

      - task: Npm@1
        displayName: "NPM install root"
        inputs:
          command: install
          verbose: false
        condition: ne(variables.NPM_CACHE_RESTORED, 'true')

      - script: |
          npm run postinstall
        displayName: "install playwright chrome"

      - script: |
          npx puppeteer browsers install chrome
        displayName: "install chrome"

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: "current"
          downloadType: "single"
          artifactName: "SurveyJSLibraryBuildCore-$(Build.BuildId)"
          downloadPath: "$(System.ArtifactsDirectory)"

      - task: CopyFiles@2
        inputs:
          SourceFolder: $(System.ArtifactsDirectory)/SurveyJSLibraryBuildCore-$(Build.BuildId)
          TargetFolder: "$(Build.SourcesDirectory)/packages/survey-core/build"

      - script: |
          cd packages/survey-angular-ui
          npm install
        displayName: "NPM install packages/survey-angular-ui"

      - script: |
          cd packages/survey-angular-ui
          npm run build
        displayName: "Build Angular"

      - script: |
          cd packages/survey-angular-ui/example
          npm install
        displayName: "NPM install examples/angular-ui"

      - script: |
          cd packages/survey-angular-ui
          npm run build:example:prod
        displayName: "Build Angular Example"

      - script: |
          cd packages/survey-angular-ui
          npm run test
        displayName: "run unit and markup tests"

      - script: |
          cd packages/survey-angular-ui
          npm run e2e:ci
        displayName: "run e2e tests"

      - bash: |
          cd packages/survey-angular-ui
          npm run testcafe:ci
        displayName: "run functional tests"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/packages/survey-angular-ui/test-results"
          Contents: "**"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/Library_Angular_E2E"
          OverWrite: true
        condition: always()
        displayName: "copy e2e artifacts"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/Library_Angular_E2E/"
          ArtifactName: "Library_Angular_E2E"
          publishLocation: "Container"
        condition: always()
        displayName: "publish e2e artifacts"

      - task: PublishTestResults@2
        displayName: "Publish test results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-angular-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "Angular End-To-End Tests"
        condition: succeededOrFailed()

      # - task: PublishPipelineArtifact@1
      #   inputs:
      #     targetPath: "$(Build.SourcesDirectory)/packages/survey-angular-ui/playwright-report"
      #     artifact: angular-playwright-report
      #     publishLocation: "pipeline"
      #   condition: succeededOrFailed()

  - job: Vue3
    dependsOn: Core
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/"
          Contents: "package.json"
          TargetFolder: "$(Build.SourcesDirectory)/Temp/"
          OverWrite: true
        displayName: "Copy package.json for cache key"

      - task: Cache@2
        inputs:
          key: "npm-cache-library | $(Build.SourcesDirectory)/Temp/package.json"
          path: $(Build.SourcesDirectory)/node_modules
          cacheHitVar: NPM_CACHE_RESTORED
        displayName: Cache NPMs

      - task: Npm@1
        displayName: "NPM install root"
        inputs:
          command: install
          verbose: false
        condition: ne(variables.NPM_CACHE_RESTORED, 'true')

      - script: |
          npm run postinstall
        displayName: "install playwright chrome"

      - script: |
          npx puppeteer browsers install chrome
        displayName: "install chrome"

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: "current"
          downloadType: "single"
          artifactName: "SurveyJSLibraryBuildCore-$(Build.BuildId)"
          downloadPath: "$(System.ArtifactsDirectory)"

      - task: CopyFiles@2
        inputs:
          SourceFolder: $(System.ArtifactsDirectory)/SurveyJSLibraryBuildCore-$(Build.BuildId)
          TargetFolder: "$(Build.SourcesDirectory)/packages/survey-core/build"

      - script: |
          cd packages/survey-vue3-ui
          npm install
        displayName: "NPM install packages/survey-vue3-ui"

      - script: |
          cd packages/survey-vue3-ui
          npm run build
        displayName: "Build Vue3"

      - script: |
          cd packages/survey-vue3-ui/example
          npm install
        displayName: "NPM install examples/angular-ui"

      - script: |
          cd packages/survey-vue3-ui/example
          npm run build
        displayName: "Build Vue3 Example"

      - script: |
          cd packages/survey-vue3-ui
          npm run test
        displayName: "run unit and markup tests"

      - script: |
          cd packages/survey-vue3-ui
          npm run e2e:ci
        displayName: "run e2e tests"

      - bash: |
          cd packages/survey-vue3-ui
          npm run testcafe:ci
        displayName: "run functional tests"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/packages/survey-vue3-ui/test-results"
          Contents: "**"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/Library_Vue3_E2E"
          OverWrite: true
        condition: always()
        displayName: "copy e2e artifacts"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/Library_Vue3_E2E/"
          ArtifactName: "Library_Vue3_E2E"
          publishLocation: "Container"
        condition: always()
        displayName: "publish e2e artifacts"

      - task: PublishTestResults@2
        displayName: "Publish test results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-vue3-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "Vue3 End-To-End Tests"
        condition: succeededOrFailed()

      # - task: PublishPipelineArtifact@1
      #   inputs:
      #     targetPath: "$(Build.SourcesDirectory)/packages/survey-vue3-ui/playwright-report"
      #     artifact: vue3-playwright-report
      #     publishLocation: "pipeline"
      #   condition: succeededOrFailed()

  - job: SurveyUI_and_CSSFrameworks
    dependsOn: Core
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/"
          Contents: "package.json"
          TargetFolder: "$(Build.SourcesDirectory)/Temp/"
          OverWrite: true
        displayName: "Copy package.json for cache key"
      - task: Cache@2
        inputs:
          key: "npm-cache-library | $(Build.SourcesDirectory)/Temp/package.json"
          path: $(Build.SourcesDirectory)/node_modules
          cacheHitVar: NPM_CACHE_RESTORED
        displayName: Cache NPM

      - task: Npm@1
        displayName: "NPM install root"
        inputs:
          command: install
          verbose: false
          workingDir: $(Build.SourcesDirectory)
        condition: ne(variables.NPM_CACHE_RESTORED, 'true')

      - script: |
          npx puppeteer browsers install chrome
        displayName: "install chrome"

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: "current"
          downloadType: "single"
          artifactName: "SurveyJSLibraryBuildCore-$(Build.BuildId)"
          downloadPath: "$(System.ArtifactsDirectory)"

      - task: CopyFiles@2
        inputs:
          SourceFolder: $(System.ArtifactsDirectory)/SurveyJSLibraryBuildCore-$(Build.BuildId)
          TargetFolder: "$(Build.SourcesDirectory)/packages/survey-core/build"

      - script: |
          cd packages/survey-js-ui
          npm install
        displayName: "NPM install packages/survey-js-ui"

      - script: |
          cd packages/survey-js-ui
          npm run build
        displayName: "Build UI"

      # - script: |
      #     cd packages/survey-js-ui
      #     npm run test
      #   displayName: "run markup tests"

      - bash: |
          cd packages/survey-js-ui
          npm run testcafe:ci
        displayName: "run functional tests"
