jobs:
  - job: AngularBuild
    displayName: "Build & Markup"
    steps:
      - template: utils/init.yml

      - template: utils/release-version.yml

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-core

      - template: utils/git-config.yml

      - script: |
          git tag -l | xargs -r git tag -d
          npm run release -- --release-as $(SurveyJSVersion)
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Core release"

      - script: npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Build Core"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-angular-ui

      - script: |
          git tag -l | xargs -r git tag -d
          npm run release -- --release-as $(SurveyJSVersion)
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
        displayName: "Angular release"

      - script: npm run build
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
        displayName: "Build Angular"

      - script: npm run test
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
        displayName: "Test Markup"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-angular-ui/example

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/packages/survey-angular-ui/build"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-angular-ui"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/"
          ArtifactName: "SurveyJSLibraryBuildAngular"
          publishLocation: "Container"

  - job: AngularTestA11YE2E
    displayName: "Test A11Y & E2E"
    steps:
      - template: utils/init.yml

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-core

      - script: npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Build Core"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-angular-ui

      - script: npm run build
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
        displayName: "Build"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-angular-ui/example

      - script: npm run build:example:prod
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
        displayName: "Build Example"

      - template: utils/playwright.yml

      - script: npm run accessibility-tests:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
        displayName: "Test A11Y"

      - script: npm run e2e:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
        displayName: "Test E2E"

      - task: PublishBuildArtifacts@1
        displayName: "Publish test artifacts"
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-angular-ui/test-results"
          ArtifactName: "Library_Angular_E2E"
          publishLocation: "Container"
        condition: always()

      - task: PublishTestResults@2
        displayName: "Publish test results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-angular-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "Angular E2E Tests"
        condition: succeededOrFailed()

  - job: AngularTestSCR
    displayName: "Test SCR"
    steps:
      - template: utils/init.yml

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-core

      - script: npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Build Core"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-angular-ui

      - script: npm run build
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
        displayName: "Build"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-angular-ui/example

      - script: npm run build:example:prod
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
        displayName: "Build Example"

      - template: utils/playwright.yml

      - script: npm run scr:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-angular-ui
        displayName: "Test"

      - task: PublishBuildArtifacts@1
        displayName: "Publish artifacts"
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-angular-ui/test-results"
          ArtifactName: "Library_Angular_SCR"
          publishLocation: "Container"
        condition: always()

      - task: PublishTestResults@2
        displayName: "Publish results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-angular-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "Angular SCR Tests"
        condition: succeededOrFailed()
