jobs:
  - job: CoreBuild
    displayName: "Build & Unit & CSS"
    steps:
      - template: utils/init.yml

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-core

      - script: npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Build"

      - script: npm run test
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Unit Tests"

      - script: npm run test:postcss
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "CSS Tests"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-core/build"
          ArtifactName: "SurveyJSLibraryBuildCore-$(Build.BuildId)"
          publishLocation: "Container"
