jobs:
  - job: PreactBuild
    displayName: "Build"
    steps:
      - template: utils/init.yml

      - template: utils/release-version.yml

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-core

      - template: utils/git-config.yml

      - script: |
          git tag -l | xargs -r git tag -d
          npm run release -- --release-as $(SurveyJSVersion)
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Core release"

      - script: npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Build Core"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-js-ui

      - script: |
          git tag -l | xargs -r git tag -d
          npm run release -- --release-as $(SurveyJSVersion)
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-js-ui
        displayName: "Preact release"

      - script: npm run build
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-js-ui
        displayName: "Build"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/packages/survey-js-ui/build"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-js-ui"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/"
          ArtifactName: "SurveyJSLibraryBuildSurveyUI"
          publishLocation: "Container"

  - job: PreactTestA11YE2E
    displayName: "Test A11Y & E2E"
    steps:
      - template: utils/init.yml

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-core

      - script: npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Build Core"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-js-ui

      - script: npm run build
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-js-ui
        displayName: "Build"

      - template: utils/playwright.yml

      - script: npm run accessibility-tests:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-js-ui
        displayName: "Test A11Y"

      - script: npm run e2e:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-js-ui
        displayName: "Test E2E"

      - task: PublishBuildArtifacts@1
        displayName: "Publish artifacts"
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-js-ui/test-results"
          ArtifactName: "Library_Preact_E2E"
          publishLocation: "Container"
        condition: always()

      - task: PublishTestResults@2
        displayName: "Publish results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-js-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "Preact E2E Tests"
        condition: succeededOrFailed()

  - job: PreactTestSCR
    displayName: "Test SCR"
    steps:
      - template: utils/init.yml

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-core

      - script: npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Build Core"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-js-ui

      - script: npm run build
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-js-ui
        displayName: "Build"

      - template: utils/playwright.yml

      - script: npm run scr:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-js-ui
        displayName: "Test"

      - task: PublishBuildArtifacts@1
        displayName: "Publish artifacts"
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-js-ui/test-results"
          ArtifactName: "Library_Preact_SCR"
          publishLocation: "Container"
        condition: always()

      - task: PublishTestResults@2
        displayName: "Publish results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-js-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "Preact SCR Tests"
        condition: succeededOrFailed()
