jobs:
  - job: VueBuild
    displayName: "Build & Markup"
    steps:
      - template: utils/init.yml

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-core

      - script: npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Build Core"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-vue3-ui

      - script: npm run build
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-vue3-ui
        displayName: "Build"

      - script: npm run test
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-vue3-ui
        displayName: "Test Markup"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-vue3-ui/build"
          ArtifactName: "LibraryBuildVue"
          StoreAsTar: true

  - job: VueTestA11YE2E
    displayName: "Test A11Y & E2E"
    steps:
      - template: utils/init.yml

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-core

      - script: npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Build Core"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-vue3-ui

      - script: npm run build
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-vue3-ui
        displayName: "Build"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-vue3-ui/example

      - script: npm run build:example:prod
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-vue3-ui
        displayName: "Build Example"

      - template: utils/playwright.yml

      - script: npm run accessibility-tests:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-vue3-ui
        displayName: "Test A11Y"

      - script: npm run e2e:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-vue3-ui
        displayName: "Test E2E"

      - task: PublishBuildArtifacts@1
        displayName: "Publish artifacts"
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-vue3-ui/test-results"
          ArtifactName: "Library_Vue_E2E"
          publishLocation: "Container"
        condition: always()

      - task: PublishTestResults@2
        displayName: "Publish results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-vue3-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "Vue3 E2E Tests"
        condition: succeededOrFailed()

  - job: VueTestSCR
    displayName: "Test SCR"
    steps:
      - template: utils/init.yml

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-core

      - script: npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
        displayName: "Build Core"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-vue3-ui

      - script: npm run build
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-vue3-ui
        displayName: "Build"

      - template: utils/npm.yml
        parameters:
          directory: $(Build.SourcesDirectory)/packages/survey-vue3-ui/example

      - script: npm run build:example:prod
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-vue3-ui
        displayName: "Build Example"

      - template: utils/playwright.yml

      - script: npm run scr:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-vue3-ui
        displayName: "Test"

      - task: PublishBuildArtifacts@1
        displayName: "Publish artifacts"
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-vue3-ui/test-results"
          ArtifactName: "Library_Vue3_SCR"
          publishLocation: "Container"
        condition: always()

      - task: PublishTestResults@2
        displayName: "Publish results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-vue3-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "Vue3 SCR Tests"
        condition: succeededOrFailed()
