export const legacyCssVariables = {
  "--sjs-general-backcolor": "--sjs2-color-bg-basic-primary", //hsl(0, 0.00%, 100.00%)",
  "--sjs-general-backcolor-dark": "--sjs2-color-bg-basic-primary-dim", //rgba(248, 248, 248, 1)",
  "--sjs-general-backcolor-dim": "--sjs2-color-bg-neutral-tertiary-dim", //rgba(243, 243, 243, 1)",
  "--sjs-general-backcolor-dim-light": "--sjs2-color-control-formbox-default-bg", //??? //rgba(249, 249, 249, 1)",
  "--sjs-general-backcolor-dim-dark": "--sjs2-color-bg-basic-secondary-dim", //rgba(243, 243, 243, 1)",
  "--sjs-general-forecolor": "--sjs2-color-fg-basic-primary", //rgba(0, 0, 0, 0.91)",
  "--sjs-general-forecolor-light": "--sjs2-color-fg-basic-secondary", //rgba(0, 0, 0, 0.45)",
  //"--sjs-general-dim-forecolor": "--sjs2-color-fg-basic-primary",//??? //rgba(0, 0, 0, 0.91)",
  //"--sjs-general-dim-forecolor-light": "--sjs2-color-fg-basic-primary",//??? //rgba(0, 0, 0, 0.45)",
  "--sjs-primary-backcolor": "--sjs2-color-bg-brand-primary", //"rgba(25, 179, 148, 1)",
  "--sjs-primary-backcolor-light": "--sjs2-color-bg-brand-secondary", //"rgba(25, 179, 148, 0.1)",
  "--sjs-primary-backcolor-dark": "--sjs2-color-bg-brand-primary-dim", //rgba(20, 164, 139, 1)",
  "--sjs-primary-forecolor": "--sjs2-color-fg-brand-on-primary", //rgba(255, 255, 255, 1)",
  "--sjs-primary-forecolor-light": "--sjs2-color-fg-brand-primary-disabled", //rgba(255, 255, 255, 0.25)",
  "--sjs-base-unit": "--sjs2-base-unit-size", //"8px"
  "--sjs-corner-radius": "--sjs2-base-unit-radius", //"4px"
  "--sjs-secondary-backcolor": "--sjs2-color-bg-accent-primary", //rgba(255, 152, 20, 1)",
  "--sjs-secondary-backcolor-light": "--sjs2-color-bg-accent-secondary", //rgba(255, 152, 20, 0.1)",
  "--sjs-secondary-backcolor-semi-light": "--sjs2-color-bg-accent-secondary-dim", //rgba(255, 152, 20, 0.25)",
  "--sjs-secondary-forecolor": "--sjs2-color-fg-accent-on-primary", //rgba(255, 255, 255, 1)",
  "--sjs-secondary-forecolor-light": "--sjs2-color-fg-accent-primary-disabled", //rgba(255, 255, 255, 0.25)",
  //"--sjs-shadow-small": "",//0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
  //"--sjs-shadow-small-reset": "",//0px 0px 0px 0px rgba(0, 0, 0, 0.15)",
  //"--sjs-shadow-medium": "",//0px 2px 6px 0px rgba(0, 0, 0, 0.1)",
  //"--sjs-shadow-large": "",//0px 8px 16px 0px rgba(0, 0, 0, 0.1)",
  //"--sjs-shadow-inner": "",//inset 0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
  //"--sjs-shadow-inner-reset": "",//inset 0px 0px 0px 0px rgba(0, 0, 0, 0.15)",
  "--sjs-border-light": "--sjs2-color-border-basic-secondary", //rgba(0, 0, 0, 0.09)",
  "--sjs-border-default": "--sjs2-color-border-basic-primary", //rgba(0, 0, 0, 0.16)",
  "--sjs-border-inside": "--sjs2-color-border-basic-secondary-overlay", //rgba(0, 0, 0, 0.16)",
  "--sjs-special-red": "--sjs2-color-bg-alert-primary", //rgba(229, 10, 62, 1)",
  "--sjs-special-red-light": "--sjs2-color-bg-alert-secondary", //rgba(229, 10, 62, 0.1)",
  "--sjs-special-red-forecolor": "--sjs2-color-fg-alert-on-primary", //rgba(255, 255, 255, 1)",
  "--sjs-special-green": "--sjs2-color-bg-positive-primary", //rgba(25, 179, 148, 1)",
  "--sjs-special-green-light": "--sjs2-color-bg-positive-secondary", //rgba(25, 179, 148, 0.1)",
  "--sjs-special-green-forecolor": "--sjs2-color-fg-positive-on-primary", //rgba(255, 255, 255, 1)",
  "--sjs-special-blue": "--sjs2-color-bg-note-primary", //rgba(67, 127, 217, 1)",
  "--sjs-special-blue-light": "--sjs2-color-bg-note-secondary", //rgba(67, 127, 217, 0.1)",
  "--sjs-special-blue-forecolor": "--sjs2-color-fg-note-on-primary", //rgba(255, 255, 255, 1)",
  "--sjs-special-yellow": "--sjs2-color-bg-warning-primary", //rgba(255, 152, 20, 1)",
  "--sjs-special-yellow-light": "--sjs2-color-bg-warning-secondary", //rgba(255, 152, 20, 0.1)",
  "--sjs-special-yellow-forecolor": "--sjs2-color-fg-warning-on-primary", //rgba(255, 255, 255, 1)",

  "--sjs-editorpanel-cornerRadius": "--sjs2-radius-semantic-form",
  "--sjs-editorpanel-backcolor": "--sjs2-color-control-formbox-default-bg",
  "--sjs-editorpanel-hovercolor": "--sjs2-color-bg-basic-secondary-dim",
  "--sjs-questionpanel-cornerRadius": "--sjs2-radius-container-panel",
  "--sjs-questionpanel-backcolor": "--sjs2-color-bg-basic-primary",
  "--sjs-questionpanel-hovercolor": "--sjs2-color-bg-basic-primary-dim",
};