export const legacyCssVariables = {
  "--sjs-general-backcolor": [
    "--sjs2-color-bg-basic-primary", //hsl(0, 0.00%, 100.00%)",
    "--sjs2-color-utility-property-grid",
    "--sjs2-color-utility-tabs",
    "--sjs2-color-utility-toolbox",
    "--sjs2-color-component-action-alert-quaternary-surface-default-bg",
    "--sjs2-color-component-action-alert-quaternary-surface-hovered-bg",
    "--sjs2-color-component-action-brand-quaternary-surface-default-bg",
    "--sjs2-color-component-action-brand-quaternary-surface-hovered-bg",
    "--sjs2-color-component-action-neutral-quaternary-surface-default-bg",
    "--sjs2-color-component-action-neutral-quaternary-surface-hovered-bg",
  ],
  "--sjs-general-backcolor-dark": "--sjs2-color-bg-basic-primary-dim", //rgba(248, 248, 248, 1)",
  "--sjs-general-backcolor-dim": ["--sjs2-color-bg-neutral-tertiary-dim",
    "--sjs2-color-utility-surface-survey-panelless",
    "--sjs2-color-utility-surface-survey"], //rgba(243, 243, 243, 1)",
  "--sjs-general-backcolor-dim-light": "--sjs2-color-bg-basic-secondary", //??? //rgba(249, 249, 249, 1)",
  "--sjs-general-backcolor-dim-dark": "--sjs2-color-bg-basic-secondary-dim", //rgba(243, 243, 243, 1)",
  "--sjs-general-forecolor": "--sjs2-color-fg-basic-primary", //rgba(0, 0, 0, 0.91)",
  "--sjs-general-forecolor-light": [
    "--sjs2-color-fg-basic-secondary", //rgba(0, 0, 0, 0.45)",
    "--sjs2-color-component-action-alert-quaternary-surface-default-icon",
    "--sjs2-color-component-action-brand-quaternary-surface-default-icon",
    "--sjs2-color-component-action-neutral-quaternary-surface-default-icon",
  ],
  //"--sjs-general-dim-forecolor": "--sjs2-color-fg-basic-primary",//??? //rgba(0, 0, 0, 0.91)",
  //"--sjs-general-dim-forecolor-light": "--sjs2-color-fg-basic-primary",//??? //rgba(0, 0, 0, 0.45)",
  "--sjs-primary-backcolor": "--sjs2-color-project-brand-600", //"rgba(25, 179, 148, 1)",
  "--sjs-primary-backcolor-light": "--sjs2-color-bg-brand-secondary", //"rgba(25, 179, 148, 0.1)",
  "--sjs-primary-backcolor-dark": "--sjs2-color-bg-brand-primary-dim", //rgba(20, 164, 139, 1)",
  "--sjs-primary-forecolor": "--sjs2-color-fg-brand-on-primary", //rgba(255, 255, 255, 1)",
  "--sjs-primary-forecolor-light": "--sjs2-color-fg-brand-primary-disabled", //rgba(255, 255, 255, 0.25)",
  "--sjs-base-unit": ["--sjs2-base-unit-size", "--sjs2-base-unit-spacing"], //"8px"
  "--sjs-corner-radius": "--sjs2-base-unit-radius", //"4px"
  "--sjs-shadow-small": [
    "--sjs2-border-effect-surface-default", //0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
    "--sjs2-border-effect-component-action-brand-tertiary-surface-default",
    "--sjs2-border-effect-component-action-brand-tertiary-surface-hovered",
    "--sjs2-border-effect-component-action-brand-tertiary-surface-disabled",
    "--sjs2-border-effect-component-action-brand-primary-default",
    "--sjs2-border-effect-component-action-brand-primary-hovered",
    "--sjs2-border-effect-component-action-brand-primary-disabled",
  ],
  "--sjs-shadow-medium": { var: "--sjs2-border-effect-floating-default", join: "," }, //0px 2px 6px 0px rgba(0, 0, 0, 0.1)",
  "--sjs-shadow-large": { var: "--sjs2-border-effect-floating-default", join: "," }, //0px 8px 16px 0px rgba(0, 0, 0, 0.1)",
  "--sjs-shadow-inner": [
    "--sjs2-border-effect-component-formbox-default", //inset 0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
    "--sjs2-border-effect-component-check-true-default",
    "--sjs2-border-effect-component-check-false-default",
  ],
  "--sjs-border-light": "--sjs2-color-border-basic-secondary", //rgba(0, 0, 0, 0.09)",
  "--sjs-border-default": "--sjs2-color-component-input-default-line", //rgba(0, 0, 0, 0.16)",
  "--sjs-border-inside": "--sjs2-color-border-basic-secondary-overlay", //rgba(0, 0, 0, 0.16)",
  "--sjs-special-red": "--sjs2-color-bg-alert-primary", //rgba(229, 10, 62, 1)",
  "--sjs-special-red-light": "--sjs2-color-bg-alert-secondary", //rgba(229, 10, 62, 0.1)",
  "--sjs-special-red-forecolor": "--sjs2-color-fg-alert-on-primary", //rgba(255, 255, 255, 1)",
  "--sjs-special-green": "--sjs2-color-bg-positive-primary", //rgba(25, 179, 148, 1)",
  "--sjs-special-green-light": "--sjs2-color-bg-positive-secondary", //rgba(25, 179, 148, 0.1)",
  "--sjs-special-green-forecolor": "--sjs2-color-fg-positive-on-primary", //rgba(255, 255, 255, 1)",
  "--sjs-special-blue": "--sjs2-color-bg-note-primary", //rgba(67, 127, 217, 1)",
  "--sjs-special-blue-light": "--sjs2-color-bg-note-secondary", //rgba(67, 127, 217, 0.1)",
  "--sjs-special-blue-forecolor": "--sjs2-color-fg-note-on-primary", //rgba(255, 255, 255, 1)",
  "--sjs-special-yellow": "--sjs2-color-bg-warning-primary", //rgba(255, 152, 20, 1)",
  "--sjs-special-yellow-light": "--sjs2-color-bg-warning-secondary", //rgba(255, 152, 20, 0.1)",
  "--sjs-special-yellow-forecolor": "--sjs2-color-fg-warning-on-primary", //rgba(255, 255, 255, 1)",

  "--sjs-editorpanel-cornerRadius": "--sjs2-radius-form",
  "--sjs-editorpanel-backcolor": "--sjs2-color-component-formbox-default-bg",
  "--sjs-editorpanel-hovercolor": "--sjs2-color-component-check-false-hovered-bg",
  "--sjs-questionpanel-cornerRadius": "--sjs2-radius-component-panel",
  "--sjs-questionpanel-backcolor": [
    "--sjs2-color-component-panel-default-bg",
    "--sjs2-color-component-action-alert-quaternary-surface-default-bg",
    "--sjs2-color-component-action-alert-quaternary-surface-hovered-bg",
    "--sjs2-color-component-action-brand-quaternary-surface-default-bg",
    "--sjs2-color-component-action-brand-quaternary-surface-hovered-bg",
    "--sjs2-color-component-action-neutral-quaternary-surface-default-bg",
    "--sjs2-color-component-action-neutral-quaternary-surface-hovered-bg",
  ],
  "--sjs-questionpanel-hovercolor": "--sjs2-color-unknown-variable-001",

  "--sjs-font-family": "--sjs2-typography-font-family-text",
  "--sjs-font-pagetitle-family": "--sjs2-typography-font-family-component-page-title",
  "--sjs-font-pagetitle-weight": "--sjs2-typography-font-weight-component-page-title",
  "--sjs-font-pagetitle-size": "--sjs2-typography-font-size-component-page-title",
  "--sjs-font-pagetitle-color": "--sjs2-color-component-page-default-title",
  "--sjs-font-pagedescription-family": "--sjs2-typography-font-family-component-page-description",
  "--sjs-font-pagedescription-weight": "--sjs2-typography-font-weight-component-page-description",
  "--sjs-font-pagedescription-size": "--sjs2-typography-font-size-component-page-description",
  "--sjs-font-pagedescription-color": "--sjs2-color-component-page-default-description",

  "--sjs-font-questiontitle-family": "--sjs2-typography-font-family-component-question-title",
  "--sjs-font-questiontitle-weight": "--sjs2-typography-font-weight-component-question-title",
  "--sjs-font-questiontitle-size": "--sjs2-typography-font-size-component-question-title",
  "--sjs-font-questiontitle-color": [
    "--sjs2-color-component-question-default-title",
    "--sjs2-color-fg-basic-primary",
  ],
  "--sjs-font-questiondescription-family": "--sjs2-typography-font-family-component-question-description",
  "--sjs-font-questiondescription-weight": "--sjs2-typography-font-weight-component-question-description",
  "--sjs-font-questiondescription-size": "--sjs2-typography-font-size-component-question-description",
  "--sjs-font-questiondescription-color": [
    "--sjs2-color-component-question-default-description",
    "--sjs2-color-component-action-alert-quaternary-surface-default-icon",
    "--sjs2-color-component-action-brand-quaternary-surface-default-icon",
    "--sjs2-color-component-action-neutral-quaternary-surface-default-icon",
  ],

  "--sjs-font-surveytitle-family": "--sjs2-typography-font-family-component-header-title",
  "--sjs-font-surveytitle-weight": "--sjs2-typography-font-weight-component-header-title",
  "--sjs-font-surveytitle-size": "--sjs2-typography-font-size-component-header-title",
  "--sjs-font-surveydescription-family": "--sjs2-typography-font-family-component-header-description",
  "--sjs-font-surveydescription-weight": "--sjs2-typography-font-weight-component-header-description",
  "--sjs-font-surveydescription-size": "--sjs2-typography-font-size-component-header-description",
  "--sjs-font-headertitle-family": "--sjs2-typography-font-family-component-header-title",
  "--sjs-font-headertitle-weight": "--sjs2-typography-font-weight-component-header-title",
  "--sjs-font-headertitle-size": "--sjs2-typography-font-size-component-header-title",
  "--sjs-font-headertitle-color": "--sjs2-color-component-header-default-title",
  "--sjs-font-headerdescription-family": "--sjs2-typography-font-family-component-header-description",
  "--sjs-font-headerdescription-weight": "--sjs2-typography-font-weight-component-header-description",
  "--sjs-font-headerdescription-size": "--sjs2-typography-font-size-component-header-description",
  "--sjs-font-headerdescription-color": "--sjs2-color-component-header-default-description",
  "--sjs-header-backcolor": "--sjs2-color-component-header-default-bg",

  "--sjs-font-editorfont-family": [
    "--sjs2-typography-font-family-component-input-content",
    "--sjs2-typography-font-family-component-label-content",
  ],
  "--sjs-font-editorfont-weight": [
    "--sjs2-typography-font-weight-component-input-content",
    "--sjs2-typography-font-weight-component-label-content",
  ],
  "--sjs-font-editorfont-size": [
    "--sjs2-typography-font-size-component-input-content",
    "--sjs2-typography-font-size-component-label-content",
  ],
  "--sjs-font-editorfont-color": [
    "--sjs2-color-component-input-default-value",
    "--sjs2-color-component-label-default-text",
  ],
  "--sjs-font-editorfont-placeholdercolor": [
    "--sjs2-color-component-input-default-placeholder",
    "--sjs2-color-component-boolean-item-false-default-value",
    "--sjs2-color-component-input-default-label"
  ],
};