export const defaultSelectListCss = {
  root: "sd-selectlist__container",
  item: "sd-selectlist__item",
  itemBody: "sd-selectlist__item-body",
  itemLabel: "sd-selectlist-item__label",
  itemSelected: "sd-selectlist__item--selected",
  itemFocused: "sd-selectlist__item--focused",
  itemHovered: "sd-selectlist__item--hovered",
  itemDisabled: "sd-selectlist__item--disabled",
  itemWithIcon: "sd-selectlist__item--with-icon",
  itemGroup: "sd-selectlist__item--group",
  itemGroupSelected: "sd-selectlist__item--group-selected",
  itemTextWrap: "sd-selectlist__item-text--wrap",
  itemIcon: "sd-selectlist__item-icon",
  itemCustomValue: "sd-selectlist__item--custom-value",
  itemMarkerIcon: "sd-selectlist-item__marker-icon",
  itemSeparator: "sd-selectlist__item-separator",
  itemsContainer: "sd-selectlist",
  itemsContainerFiltering: "sd-selectlist--filtering",
  filter: "sd-selectlist__filter",
  filterBox: "sd-selectlist-filter__box",
  filterIcon: "sd-selectlist__filter-icon",
  filterInput: "sd-selectlist__input",
  searchClearButtonIcon: "sd-selectlist__filter-clear-button",
  loadingIndicator: "sd-selectlist__loading-indicator",
  emptyContainer: "sd-selectlist__empty-container",
  emptyText: "sd-selectlist__empty-text"
};