version:="1.8.46b"
copy:
    cd .. && npm run build_vue_prod
    mkdir -p ~/dev/surveyresearch/static/js/{{version}}/
    mkdir -p ~/dev/surveyresearch/static/css/{{version}}/
    cp -rf ~/dev/survey-library/build/survey-vue/*.min.js ~/dev/surveyresearch/static/js/{{version}}/
    cp -rf ~/dev/survey-library/build/survey-vue/*.min.css ~/dev/surveyresearch/static/css/{{version}}/
    cp -rf ~/dev/survey-library/build/survey-vue/*.css ~/dev/sradmin/src/assets/css

# upstream is the master branch of original repo
sync_upstream:
    git co master
    git fetch upstream 
    git pull upstream master
