// Auto-generated theme: borderless
export default {
  "themeName": "borderless",
  "colorPalette": "dark",
  "isPanelless": true,
  "cssVariables": {
    "--sjs2-color-project-brand-600": "rgba(114, 187, 255, 1)",
    "--sjs2-color-utility-body": "var(--sjs2-palette-gray-999)",
    "--sjs2-color-utility-sheet": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-utility-a11y": "rgba(from var(--sjs2-palette-blue-400) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-utility-scrollbar": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-utility-toolbox": "rgba(43, 48, 63, 1)",
    "--sjs2-color-utility-property-grid": "rgba(43, 48, 63, 1)",
    "--sjs2-color-utility-tabs": "rgba(43, 48, 63, 1)",
    "--sjs2-color-utility-surface-survey": "rgba(33, 37, 51, 1)",
    "--sjs2-color-utility-surface-designer": "#161519",
    "--sjs2-color-utility-surface-presets-manager": "#161519",
    "--sjs2-color-utility-shadow-surface-default": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-utility-shadow-surface-dragging": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-floating-default": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-bg-basic-primary": "rgba(43, 48, 63, 1)",
    "--sjs2-color-bg-basic-secondary": "rgba(36, 41, 55, 1)",
    "--sjs2-color-bg-basic-tertiary": "#202531",
    "--sjs2-color-bg-basic-primary-dim": "rgba(50, 55, 72, 1)",
    "--sjs2-color-bg-basic-secondary-dim": "rgba(40, 46, 61, 1)",
    "--sjs2-color-bg-basic-tertiary-dim": "#202531",
    "--sjs2-color-bg-basic-primary-disabled": "#1b1f2a",
    "--sjs2-color-bg-neutral-secondary": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-neutral-secondary-dim": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x020))",
    "--sjs2-color-bg-neutral-tertiary-dim": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-neutral-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-brand-secondary": "rgba(114, 187, 255, 0.1)",
    "--sjs2-color-bg-brand-primary-dim": "rgba(151, 205, 255, 1)",
    "--sjs2-color-bg-brand-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-note-primary": "rgba(91, 151, 242, 1)",
    "--sjs2-color-bg-note-secondary": "rgba(91, 151, 242, 0.1)",
    "--sjs2-color-bg-note-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-positive-primary": "rgba(36, 197, 164, 1)",
    "--sjs2-color-bg-positive-secondary": "rgba(36, 197, 164, 0.1)",
    "--sjs2-color-bg-positive-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-warning-secondary": "rgba(255, 152, 20, 0.1)",
    "--sjs2-color-bg-warning-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-alert-primary": "rgba(254, 76, 108, 1)",
    "--sjs2-color-bg-alert-secondary": "rgba(254, 76, 108, 0.1)",
    "--sjs2-color-bg-alert-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-fg-basic-primary": "#d9edff",
    "--sjs2-color-fg-brand-on-primary": "rgba(32, 32, 32, 1)",
    "--sjs2-color-fg-note-on-primary": "rgba(48, 48, 48, 1)",
    "--sjs2-color-fg-positive-on-primary": "rgba(48, 48, 48, 1)",
    "--sjs2-color-fg-warning-on-primary": "rgba(48, 48, 48, 1)",
    "--sjs2-color-fg-alert-on-primary": "rgba(48, 48, 48, 1)",
    "--sjs2-color-border-basic-secondary": "rgba(55, 62, 79, 1)",
    "--sjs2-color-border-basic-secondary-overlay": "rgba(158,189,241,0.08)",
    "--sjs2-color-border-basic-secondary-disabled": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-disabled))",
    "--sjs2-color-component-buttongroup-item-false-readonly-bg": "rgba(from var(--sjs2-color-bg-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-true-default-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-true-readonly-bg": "rgba(from var(--sjs2-color-bg-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-border-spread-form-default": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-form-hovered": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-form-pressed": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-form-readonly": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-form-design": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-surface-default": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-surface-disabled": "var(--sjs2-border-width-x000)",
    "--sjs2-border-effect-component-formbox-focused": "var(--sjs2-border-offset-x-form-focused) var(--sjs2-border-offset-y-form-focused) var(--sjs2-border-blur-form-focused) var(--sjs2-border-spread-form-focused) var(--sjs2-color-component-formbox-focused-border)",
    "--sjs2-border-effect-component-formbox-invalid-focused": "var(--sjs2-border-offset-x-form-invalid-focused) var(--sjs2-border-offset-y-form-invalid-focused) var(--sjs2-border-blur-form-invalid-focused) var(--sjs2-border-spread-form-invalid-focused) var(--sjs2-color-component-formbox-invalid-focused-border)",
    "--sjs2-border-effect-component-formbox-highlighted": "var(--sjs2-border-offset-x-form-highlighted) var(--sjs2-border-offset-y-form-highlighted) var(--sjs2-border-blur-form-highlighted) var(--sjs2-border-spread-form-highlighted) var(--sjs2-color-component-formbox-highlighted-border)",
    "--sjs2-border-effect-surface-default": "0px 0px 0px 0px rgba(0, 0, 0, 0.35)",
    "--sjs2-border-effect-floating-default": "0px 2px 6px 0px rgba(0, 0, 0, 0.2), 0px 8px 16px 0px rgba(0, 0, 0, 0.2)"
  }
};
