// Auto-generated theme: borderless
export default {
  "themeName": "borderless",
  "colorPalette": "light",
  "isPanelless": true,
  "cssVariables": {
    "--sjs2-color-project-brand-600": "rgba(35, 101, 200, 1)",
    "--sjs2-color-utility-surface-survey": "rgba(231, 240, 255, 1)",
    "--sjs2-color-utility-surface-designer": "rgba(231, 240, 255, 1)",
    "--sjs2-color-bg-basic-secondary": "rgba(238, 245, 255, 1)",
    "--sjs2-color-bg-basic-primary-dim": "rgba(241, 246, 255, 1)",
    "--sjs2-color-bg-basic-secondary-dim": "rgba(223, 233, 250, 1)",
    "--sjs2-color-bg-neutral-tertiary-dim": "rgba(231, 240, 255, 1)",
    "--sjs2-color-bg-brand-secondary": "rgba(35, 101, 200, 0.1)",
    "--sjs2-color-bg-brand-primary-dim": "rgba(26, 86, 175, 1)",
    "--sjs2-color-bg-note-secondary": "rgba(67, 127, 217, 0.1)",
    "--sjs2-color-bg-positive-secondary": "rgba(25, 179, 148, 0.1)",
    "--sjs2-color-bg-warning-secondary": "rgba(255, 152, 20, 0.1)",
    "--sjs2-color-bg-alert-secondary": "rgba(229, 10, 62, 0.1)",
    "--sjs2-color-fg-basic-primary": "#010915",
    "--sjs2-color-fg-brand-primary-disabled": "rgba(255, 255, 255, 0.25)",
    "--sjs2-color-border-basic-secondary": "rgba(220, 229, 241, 1)",
    "--sjs2-color-border-basic-secondary-overlay": "rgba(4,7,10,0.16)",
    "--sjs2-border-effect-component-formbox-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-formbox-default-border)",
    "--sjs2-border-effect-component-formbox-hovered": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-formbox-hovered-border)",
    "--sjs2-border-effect-component-formbox-focused": "0px 0px 0px var(--sjs2-border-width-x200) var(--sjs2-color-component-formbox-focused-border)",
    "--sjs2-border-effect-component-formbox-invalid-focused": "0px 0px 0px var(--sjs2-border-width-x200) var(--sjs2-color-component-formbox-invalid-focused-border)",
    "--sjs2-border-effect-component-formbox-highlighted": "0px 0px 0px var(--sjs2-border-width-x200) var(--sjs2-color-component-formbox-highlighted-border)",
    "--sjs2-border-effect-component-formbox-design": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-formbox-design-border)",
    "--sjs2-border-effect-component-check-false-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-false-default-border)",
    "--sjs2-border-effect-component-check-false-hovered": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-false-hovered-border)",
    "--sjs2-border-effect-component-check-false-design": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-false-design-border)",
    "--sjs2-border-effect-component-check-true-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-true-default-border)",
    "--sjs2-border-effect-component-check-true-hovered": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-true-hovered-border)",
    "--sjs2-border-effect-component-toggle-false-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-toggle-false-default-border)",
    "--sjs2-border-effect-component-toggle-false-hovered": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-toggle-false-hovered-border)",
    "--sjs2-border-effect-component-toggle-true-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-toggle-true-default-border)",
    "--sjs2-border-effect-component-toggle-true-hovered": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-toggle-true-hovered-border)",
    "--sjs2-border-effect-component-boolean-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-boolean-default-border)",
    "--sjs2-border-effect-component-boolean-design": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-boolean-design-border)",
    "--sjs2-border-effect-surface-default": "",
    "--sjs2-border-effect-surface-disabled": "0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-utility-shadow-surface-disabled)",
    "--sjs2-border-effect-floating-default": "0px 2px 6px 0px rgba(0, 0, 0, 0.1), 0px 8px 16px 0px rgba(0, 0, 0, 0.1)",
    "--sjs2-color-project-brand-400": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 1.2))",
    "--sjs2-color-project-brand-700": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 0.85))",
    "--sjs2-color-project-brand-800": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 0.75))",
    "--sjs2-color-bg-static-2-primary-dim": "hsl(from var(--sjs2-palette-gray-100) h s calc(l * 1.1))"
  }
};
