// Auto-generated theme: borderless
export default {
  "themeName": "borderless",
  "colorPalette": "dark",
  "cssVariables": {
    "--sjs2-color-project-brand-600": "rgba(114, 187, 255, 1)",
    "--sjs2-color-utility-body": "var(--sjs2-palette-gray-999)",
    "--sjs2-color-utility-sheet": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-utility-a11y": "rgba(from var(--sjs2-palette-blue-400) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-utility-scrollbar": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-utility-toolbox": "rgba(43, 48, 63, 1)",
    "--sjs2-color-utility-property-grid": "rgba(43, 48, 63, 1)",
    "--sjs2-color-utility-tabs": "rgba(43, 48, 63, 1)",
    "--sjs2-color-utility-surface-survey": "rgba(33, 37, 51, 1)",
    "--sjs2-color-utility-surface-survey-panelless": "rgba(33, 37, 51, 1)",
    "--sjs2-color-utility-surface-designer": "#161519",
    "--sjs2-color-utility-shadow-surface-default": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-utility-shadow-surface-dragging": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-floating-default": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-bg-basic-primary": "rgba(43, 48, 63, 1)",
    "--sjs2-color-bg-basic-secondary": "rgba(36, 41, 55, 1)",
    "--sjs2-color-bg-basic-primary-dim": "rgba(50, 55, 72, 1)",
    "--sjs2-color-bg-basic-secondary-dim": "rgba(40, 46, 61, 1)",
    "--sjs2-color-bg-neutral-tertiary-dim": "rgba(33, 37, 51, 1)",
    "--sjs2-color-bg-brand-secondary": "rgba(114, 187, 255, 0.1)",
    "--sjs2-color-bg-brand-primary-dim": "rgba(151, 205, 255, 1)",
    "--sjs2-color-bg-note-primary": "rgba(91, 151, 242, 1)",
    "--sjs2-color-bg-note-secondary": "rgba(91, 151, 242, 0.1)",
    "--sjs2-color-bg-positive-primary": "rgba(36, 197, 164, 1)",
    "--sjs2-color-bg-positive-secondary": "rgba(36, 197, 164, 0.1)",
    "--sjs2-color-bg-warning-secondary": "rgba(255, 152, 20, 0.1)",
    "--sjs2-color-bg-alert-primary": "rgba(254, 76, 108, 1)",
    "--sjs2-color-bg-alert-secondary": "rgba(254, 76, 108, 0.1)",
    "--sjs2-color-fg-basic-primary": "#d9edff",
    "--sjs2-color-fg-brand-on-primary": "rgba(32, 32, 32, 1)",
    "--sjs2-color-fg-brand-primary-disabled": "rgba(32, 32, 32, 0.25)",
    "--sjs2-color-fg-note-on-primary": "rgba(48, 48, 48, 1)",
    "--sjs2-color-fg-positive-on-primary": "rgba(48, 48, 48, 1)",
    "--sjs2-color-fg-warning-on-primary": "rgba(48, 48, 48, 1)",
    "--sjs2-color-fg-alert-on-primary": "rgba(48, 48, 48, 1)",
    "--sjs2-color-border-basic-secondary": "rgba(55, 62, 79, 1)",
    "--sjs2-color-border-basic-secondary-overlay": "rgba(158,189,241,0.08)",
    "--sjs2-color-component-input-default-line": "rgba(65, 72, 90, 1)",
    "--sjs2-border-effect-component-formbox-default": "",
    "--sjs2-border-effect-component-formbox-hovered": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-formbox-hovered-border)",
    "--sjs2-border-effect-component-formbox-readonly": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-formbox-readonly-border)",
    "--sjs2-border-effect-component-formbox-design": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-formbox-design-border)",
    "--sjs2-border-effect-component-check-false-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-false-default-border)",
    "--sjs2-border-effect-component-check-false-hovered": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-false-hovered-border)",
    "--sjs2-border-effect-component-check-false-design": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-false-design-border)",
    "--sjs2-border-effect-component-check-false-readonly": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-false-readonly-border)",
    "--sjs2-border-effect-component-check-true-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-true-default-border)",
    "--sjs2-border-effect-component-check-true-hovered": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-check-true-hovered-border)",
    "--sjs2-border-effect-component-toggle-false-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-toggle-false-default-border)",
    "--sjs2-border-effect-component-toggle-false-hovered": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-toggle-false-hovered-border)",
    "--sjs2-border-effect-component-toggle-true-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-toggle-true-default-border)",
    "--sjs2-border-effect-component-toggle-true-hovered": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-toggle-true-hovered-border)",
    "--sjs2-border-effect-component-boolean-default": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-boolean-default-border)",
    "--sjs2-border-effect-component-boolean-readonly": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-boolean-readonly-border)",
    "--sjs2-border-effect-component-boolean-design": "inset 0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-component-boolean-design-border)",
    "--sjs2-border-effect-surface-default": "",
    "--sjs2-border-effect-surface-disabled": "0px 0px 0px var(--sjs2-border-width-x000) var(--sjs2-color-utility-shadow-surface-disabled)",
    "--sjs2-border-effect-floating-default": "0px 2px 6px 0px rgba(0, 0, 0, 0.2), 0px 8px 16px 0px rgba(0, 0, 0, 0.2)",
    "--sjs2-color-project-brand-400": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 1.2))",
    "--sjs2-color-project-brand-700": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 0.85))",
    "--sjs2-color-project-brand-800": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 0.75))",
    "--sjs2-color-bg-static-2-primary-dim": "hsl(from var(--sjs2-palette-gray-100) h s calc(l * 1.1))"
  }
};
