// Auto-generated theme: borderless
export default {
  "themeName": "borderless",
  "colorPalette": "light",
  "isPanelless": true,
  "cssVariables": {
    "--sjs2-color-project-brand-600": "rgba(35, 101, 200, 1)",
    "--sjs2-color-utility-surface-survey": "rgba(231, 240, 255, 1)",
    "--sjs2-color-utility-surface-designer": "rgba(231, 240, 255, 1)",
    "--sjs2-color-bg-basic-secondary": "rgba(238, 245, 255, 1)",
    "--sjs2-color-bg-basic-primary-dim": "rgba(241, 246, 255, 1)",
    "--sjs2-color-bg-basic-secondary-dim": "rgba(223, 233, 250, 1)",
    "--sjs2-color-bg-neutral-tertiary-dim": "rgba(231, 240, 255, 1)",
    "--sjs2-color-bg-brand-secondary": "rgba(35, 101, 200, 0.1)",
    "--sjs2-color-bg-brand-primary-dim": "rgba(26, 86, 175, 1)",
    "--sjs2-color-bg-note-secondary": "rgba(67, 127, 217, 0.1)",
    "--sjs2-color-bg-positive-secondary": "rgba(25, 179, 148, 0.1)",
    "--sjs2-color-bg-warning-secondary": "rgba(255, 152, 20, 0.1)",
    "--sjs2-color-bg-alert-secondary": "rgba(229, 10, 62, 0.1)",
    "--sjs2-color-fg-basic-primary": "#010915",
    "--sjs2-color-fg-brand-primary-disabled": "rgba(255, 255, 255, 0.25)",
    "--sjs2-color-border-basic-secondary": "rgba(220, 229, 241, 1)",
    "--sjs2-color-border-basic-secondary-overlay": "rgba(4,7,10,0.16)",
    "--sjs2-color-component-buttongroup-item-false-readonly-bg": "rgba(from var(--sjs2-color-bg-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-true-default-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-true-readonly-bg": "rgba(from var(--sjs2-color-bg-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-border-spread-form-default": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-form-hovered": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-form-pressed": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-form-design": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-surface-default": "var(--sjs2-border-width-x000)",
    "--sjs2-border-spread-surface-disabled": "var(--sjs2-border-width-x000)",
    "--sjs2-border-effect-component-formbox-focused": "var(--sjs2-border-offset-x-form-focused) var(--sjs2-border-offset-y-form-focused) var(--sjs2-border-blur-form-focused) var(--sjs2-border-spread-form-focused) var(--sjs2-color-component-formbox-focused-border)",
    "--sjs2-border-effect-component-formbox-invalid-focused": "var(--sjs2-border-offset-x-form-invalid-focused) var(--sjs2-border-offset-y-form-invalid-focused) var(--sjs2-border-blur-form-invalid-focused) var(--sjs2-border-spread-form-invalid-focused) var(--sjs2-color-component-formbox-invalid-focused-border)",
    "--sjs2-border-effect-component-formbox-highlighted": "var(--sjs2-border-offset-x-form-highlighted) var(--sjs2-border-offset-y-form-highlighted) var(--sjs2-border-blur-form-highlighted) var(--sjs2-border-spread-form-highlighted) var(--sjs2-color-component-formbox-highlighted-border)",
    "--sjs2-border-effect-surface-default": "0px 0px 0px 0px rgba(0, 0, 0, 0.15)",
    "--sjs2-border-effect-floating-default": "0px 2px 6px 0px rgba(0, 0, 0, 0.1), 0px 8px 16px 0px rgba(0, 0, 0, 0.1)"
  }
};
