// Auto-generated theme: contrast
export default {
  "themeName": "contrast",
  "colorPalette": "light",
  "cssVariables": {
    "--sjs2-color-project-brand-600": "#3A179E",
    "--sjs2-color-project-brand-700": "lch(from var(--sjs2-color-project-brand-600) calc(l * 0.85) c h)",
    "--sjs2-color-utility-surface-designer": "#F4F2FB",
    "--sjs2-color-utility-shadow-surface-dragging": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-utility-shadow-floating-default": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x020))",
    "--sjs2-color-bg-basic-secondary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x005))",
    "--sjs2-color-bg-basic-tertiary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-basic-primary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x005))",
    "--sjs2-color-bg-basic-secondary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-basic-tertiary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-basic-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-brand-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-note-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-neutral-secondary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-neutral-tertiary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x000))",
    "--sjs2-color-bg-neutral-secondary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-neutral-tertiary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x005))",
    "--sjs2-color-bg-neutral-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-positive-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-warning-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-alert-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-fg-basic-primary-disabled": "rgba(from var(--sjs2-color-fg-basic-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-basic-secondary-disabled": "rgba(from var(--sjs2-color-fg-basic-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-basic-tertiary-disabled": "rgba(from var(--sjs2-color-fg-basic-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-neutral-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-fg-neutral-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-brand-primary": "var(--sjs2-color-project-brand-600)",
    "--sjs2-color-fg-brand-primary-dim": "var(--sjs2-color-project-brand-700)",
    "--sjs2-color-fg-brand-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-note-primary": "var(--sjs2-palette-blue-600)",
    "--sjs2-color-fg-note-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-positive-primary": "var(--sjs2-palette-green-600)",
    "--sjs2-color-fg-positive-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-warning-primary": "var(--sjs2-palette-yellow-600)",
    "--sjs2-color-fg-warning-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-alert-primary": "var(--sjs2-palette-red-600)",
    "--sjs2-color-fg-alert-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-component-action-alert-tertiary-muted-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-alert-tertiary-muted-surface-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-brand-tertiary-muted-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-brand-tertiary-muted-surface-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-quaternary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-surface-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-surface-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-quaternary-surface-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-formbox-hovered-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-buttongroup-item-false-default-bg": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-false-default-value": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-false-disabled-value": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-buttongroup-item-false-readonly-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-buttongroup-item-true-disabled-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-check-true-default-icon": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-check-true-disabled-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-check-true-disabled-icon": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-check-true-hovered-icon": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-false-disabled-thumb": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-toggle-true-default-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-true-disabled-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-true-readonly-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-true-hovered-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-toggle-true-hovered-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-slider-design-fg": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-boolean-item-false-disabled-value": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-boolean-item-false-readonly-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-boolean-item-true-disabled-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-boolean-disabled-border": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-boolean-readonly-border": "var(--sjs2-palette-gray-250)",
    "--sjs2-opacity-hovered": "var(--sjs2-opacity-x100)",
    "--sjs2-opacity-pressed": "var(--sjs2-opacity-x100)",
    "--sjs2-border-effect-component-formbox-invalid-focused": "inset 0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-formbox-invalid-focused-border)",
    "--sjs2-border-effect-surface-default": "0px 2px 4px var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-surface-default)",
    "--sjs2-border-effect-floating-default": "0px 6px 12px 4px var(--sjs2-color-utility-shadow-floating-default)",
    "--sjs2-color-project-brand-400": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 1.1))",
    "--sjs2-color-project-brand-800": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 0.75))",
    "--sjs2-color-bg-static-2-primary-dim": "hsl(from var(--sjs2-palette-gray-100) h s calc(l * 1.1))"
  }
};
