// Auto-generated theme: default
export default {
  "themeName": "default",
  "iconSet": "v2",
  "isLight": true,
  "cssVariables": {
    "--sjs2-base-unit-size": "8px",
    "--sjs2-base-unit-spacing": "8px",
    "--sjs2-base-unit-radius": "8px",
    "--sjs2-base-unit-border-width": "1px",
    "--sjs2-base-unit-font-size": "8px",
    "--sjs2-base-unit-line-height": "8px",
    "--sjs2-base-unit-opacity": "1%",
    "--sjs2-base-unit-scale": "1%",
    "--sjs2-scale-x000": "calc(var(--sjs2-base-unit-scale) * 0)",
    "--sjs2-scale-x025": "calc(var(--sjs2-base-unit-scale) * 25)",
    "--sjs2-scale-x050": "calc(var(--sjs2-base-unit-scale) * 50)",
    "--sjs2-scale-x075": "calc(var(--sjs2-base-unit-scale) * 75)",
    "--sjs2-scale-x095": "calc(var(--sjs2-base-unit-scale) * 95)",
    "--sjs2-scale-x100": "calc(var(--sjs2-base-unit-scale) * 100)",
    "--sjs2-scale-x200": "calc(var(--sjs2-base-unit-scale) * 200)",
    "--sjs2-size-x000": "calc(var(--sjs2-base-unit-size) * 0)",
    "--sjs2-size-x025": "calc(var(--sjs2-base-unit-size) * 0.25)",
    "--sjs2-size-x050": "calc(var(--sjs2-base-unit-size) * 0.50)",
    "--sjs2-size-x075": "calc(var(--sjs2-base-unit-size) * 0.75)",
    "--sjs2-size-x100": "calc(var(--sjs2-base-unit-size) * 1)",
    "--sjs2-size-x150": "calc(var(--sjs2-base-unit-size) * 1.50)",
    "--sjs2-size-x200": "calc(var(--sjs2-base-unit-size) * 2)",
    "--sjs2-size-x250": "calc(var(--sjs2-base-unit-size) * 2.50)",
    "--sjs2-size-x300": "calc(var(--sjs2-base-unit-size) * 3)",
    "--sjs2-size-x350": "calc(var(--sjs2-base-unit-size) * 3.50)",
    "--sjs2-size-x400": "calc(var(--sjs2-base-unit-size) * 4)",
    "--sjs2-size-x500": "calc(var(--sjs2-base-unit-size) * 5)",
    "--sjs2-size-x600": "calc(var(--sjs2-base-unit-size) * 6)",
    "--sjs2-size-x700": "calc(var(--sjs2-base-unit-size) * 7)",
    "--sjs2-size-x800": "calc(var(--sjs2-base-unit-size) * 8)",
    "--sjs2-size-x900": "calc(var(--sjs2-base-unit-size) * 9)",
    "--sjs2-size-x1000": "calc(var(--sjs2-base-unit-size) * 10)",
    "--sjs2-size-x1100": "calc(var(--sjs2-base-unit-size) * 11)",
    "--sjs2-size-x1200": "calc(var(--sjs2-base-unit-size) * 12)",
    "--sjs2-size-x1300": "calc(var(--sjs2-base-unit-size) * 13)",
    "--sjs2-size-x1400": "calc(var(--sjs2-base-unit-size) * 14)",
    "--sjs2-size-x1500": "calc(var(--sjs2-base-unit-size) * 15)",
    "--sjs2-radius-x000": "calc(var(--sjs2-base-unit-radius) * 0)",
    "--sjs2-radius-x025": "calc(var(--sjs2-base-unit-radius) * 0.25)",
    "--sjs2-radius-x050": "calc(var(--sjs2-base-unit-radius) * 0.50)",
    "--sjs2-radius-x075": "calc(var(--sjs2-base-unit-radius) * 0.75)",
    "--sjs2-radius-x100": "calc(var(--sjs2-base-unit-radius) * 1)",
    "--sjs2-radius-x150": "calc(var(--sjs2-base-unit-radius) * 1.50)",
    "--sjs2-radius-x200": "calc(var(--sjs2-base-unit-radius) * 2)",
    "--sjs2-radius-x250": "calc(var(--sjs2-base-unit-radius) * 2.50)",
    "--sjs2-radius-x300": "calc(var(--sjs2-base-unit-radius) * 3)",
    "--sjs2-radius-x400": "calc(var(--sjs2-base-unit-radius) * 4)",
    "--sjs2-radius-x500": "calc(var(--sjs2-base-unit-radius) * 5)",
    "--sjs2-radius-x600": "calc(var(--sjs2-base-unit-radius) * 6)",
    "--sjs2-radius-x700": "calc(var(--sjs2-base-unit-radius) * 7)",
    "--sjs2-radius-x800": "calc(var(--sjs2-base-unit-radius) * 8)",
    "--sjs2-radius-round": "9999px",
    "--sjs2-spacing-x000": "calc(var(--sjs2-base-unit-spacing) * 0)",
    "--sjs2-spacing-x025": "calc(var(--sjs2-base-unit-spacing) * 0.25)",
    "--sjs2-spacing-x050": "calc(var(--sjs2-base-unit-spacing) * 0.50)",
    "--sjs2-spacing-x075": "calc(var(--sjs2-base-unit-spacing) * 0.75)",
    "--sjs2-spacing-x100": "calc(var(--sjs2-base-unit-spacing) * 1)",
    "--sjs2-spacing-x150": "calc(var(--sjs2-base-unit-spacing) * 1.5)",
    "--sjs2-spacing-x200": "calc(var(--sjs2-base-unit-spacing) * 2)",
    "--sjs2-spacing-x250": "calc(var(--sjs2-base-unit-spacing) * 2.50)",
    "--sjs2-spacing-x300": "calc(var(--sjs2-base-unit-spacing) * 3)",
    "--sjs2-spacing-x400": "calc(var(--sjs2-base-unit-spacing) * 4)",
    "--sjs2-spacing-x500": "calc(var(--sjs2-base-unit-spacing) * 5)",
    "--sjs2-spacing-x550": "calc(var(--sjs2-base-unit-spacing) * 5.5)",
    "--sjs2-spacing-x600": "calc(var(--sjs2-base-unit-spacing) * 6)",
    "--sjs2-spacing-x700": "calc(var(--sjs2-base-unit-spacing) * 7)",
    "--sjs2-spacing-x800": "calc(var(--sjs2-base-unit-spacing) * 8)",
    "--sjs2-spacing-negative-x025": "calc(var(--sjs2-base-unit-spacing) * -0.25)",
    "--sjs2-spacing-negative-x050": "calc(var(--sjs2-base-unit-spacing) * -0.50)",
    "--sjs2-spacing-negative-x075": "calc(var(--sjs2-base-unit-spacing) * -0.75)",
    "--sjs2-spacing-negative-x100": "calc(var(--sjs2-base-unit-spacing) * -1)",
    "--sjs2-spacing-negative-x150": "calc(var(--sjs2-base-unit-spacing) * -1.5)",
    "--sjs2-spacing-negative-x200": "calc(var(--sjs2-base-unit-spacing) * -2)",
    "--sjs2-spacing-negative-x250": "calc(var(--sjs2-base-unit-spacing) * -2.50)",
    "--sjs2-spacing-negative-x300": "calc(var(--sjs2-base-unit-spacing) * -3)",
    "--sjs2-spacing-negative-x400": "calc(var(--sjs2-base-unit-spacing) * -4)",
    "--sjs2-spacing-negative-x500": "calc(var(--sjs2-base-unit-spacing) * -5)",
    "--sjs2-spacing-negative-x600": "calc(var(--sjs2-base-unit-spacing) * -6)",
    "--sjs2-spacing-negative-x700": "calc(var(--sjs2-base-unit-spacing) * -7)",
    "--sjs2-spacing-negative-x800": "calc(var(--sjs2-base-unit-spacing) * -8)",
    "--sjs2-opacity-x000": "calc(var(--sjs2-base-unit-opacity) * 0)",
    "--sjs2-opacity-x005": "calc(var(--sjs2-base-unit-opacity) * 5)",
    "--sjs2-opacity-x010": "calc(var(--sjs2-base-unit-opacity) * 10)",
    "--sjs2-opacity-x015": "calc(var(--sjs2-base-unit-opacity) * 15)",
    "--sjs2-opacity-x020": "calc(var(--sjs2-base-unit-opacity) * 20)",
    "--sjs2-opacity-x025": "calc(var(--sjs2-base-unit-opacity) * 25)",
    "--sjs2-opacity-x030": "calc(var(--sjs2-base-unit-opacity) * 30)",
    "--sjs2-opacity-x035": "calc(var(--sjs2-base-unit-opacity) * 35)",
    "--sjs2-opacity-x040": "calc(var(--sjs2-base-unit-opacity) * 40)",
    "--sjs2-opacity-x045": "calc(var(--sjs2-base-unit-opacity) * 45)",
    "--sjs2-opacity-x050": "calc(var(--sjs2-base-unit-opacity) * 50)",
    "--sjs2-opacity-x055": "calc(var(--sjs2-base-unit-opacity) * 55)",
    "--sjs2-opacity-x060": "calc(var(--sjs2-base-unit-opacity) * 60)",
    "--sjs2-opacity-x065": "calc(var(--sjs2-base-unit-opacity) * 65)",
    "--sjs2-opacity-x070": "calc(var(--sjs2-base-unit-opacity) * 70)",
    "--sjs2-opacity-x075": "calc(var(--sjs2-base-unit-opacity) * 75)",
    "--sjs2-opacity-x080": "calc(var(--sjs2-base-unit-opacity) * 80)",
    "--sjs2-opacity-x085": "calc(var(--sjs2-base-unit-opacity) * 85)",
    "--sjs2-opacity-x090": "calc(var(--sjs2-base-unit-opacity) * 90)",
    "--sjs2-opacity-x095": "calc(var(--sjs2-base-unit-opacity) * 95)",
    "--sjs2-opacity-x100": "calc(var(--sjs2-base-unit-opacity) * 100)",
    "--sjs2-border-width-x000": "calc(var(--sjs2-base-unit-border-width) * 0)",
    "--sjs2-border-width-x100": "calc(var(--sjs2-base-unit-border-width) * 1)",
    "--sjs2-border-width-x200": "calc(var(--sjs2-base-unit-border-width) * 2)",
    "--sjs2-border-width-x400": "calc(var(--sjs2-base-unit-border-width) * 4)",
    "--sjs2-font-weight-regular": "400",
    "--sjs2-font-weight-medium": "500",
    "--sjs2-font-weight-semibold": "600",
    "--sjs2-font-weight-bold": "700",
    "--sjs2-font-size-x000": "calc(var(--sjs2-base-unit-font-size) * 0)",
    "--sjs2-font-size-x100": "calc(var(--sjs2-base-unit-font-size) * 1)",
    "--sjs2-font-size-x150": "calc(var(--sjs2-base-unit-font-size) * 1.5)",
    "--sjs2-font-size-x200": "calc(var(--sjs2-base-unit-font-size) * 2)",
    "--sjs2-font-size-x250": "calc(var(--sjs2-base-unit-font-size) * 2.5)",
    "--sjs2-font-size-x300": "calc(var(--sjs2-base-unit-font-size) * 3)",
    "--sjs2-font-size-x350": "calc(var(--sjs2-base-unit-font-size) * 3.5)",
    "--sjs2-font-size-x400": "calc(var(--sjs2-base-unit-font-size) * 4)",
    "--sjs2-font-size-x500": "calc(var(--sjs2-base-unit-font-size) * 5)",
    "--sjs2-font-size-x600": "calc(var(--sjs2-base-unit-font-size) * 6)",
    "--sjs2-line-height-x000": "calc(var(--sjs2-base-unit-line-height) * 0)",
    "--sjs2-line-height-x100": "calc(var(--sjs2-base-unit-line-height) * 1)",
    "--sjs2-line-height-x200": "calc(var(--sjs2-base-unit-line-height) * 2)",
    "--sjs2-line-height-x300": "calc(var(--sjs2-base-unit-line-height) * 3)",
    "--sjs2-line-height-x400": "calc(var(--sjs2-base-unit-line-height) * 4)",
    "--sjs2-line-height-x500": "calc(var(--sjs2-base-unit-line-height) * 5)",
    "--sjs2-line-height-x600": "calc(var(--sjs2-base-unit-line-height) * 6)",
    "--sjs2-text-case-default": "none",
    "--sjs2-text-case-uppercase": "uppercase",
    "--sjs2-palette-gray-100": "#F5F5F5",
    "--sjs2-palette-gray-150": "#EDEDED",
    "--sjs2-palette-gray-200": "#E5E5E5",
    "--sjs2-palette-gray-250": "#D4D4D4",
    "--sjs2-palette-gray-300": "#CDCDCD",
    "--sjs2-palette-gray-400": "#B3B2B2",
    "--sjs2-palette-gray-500": "#8E8E8E",
    "--sjs2-palette-gray-600": "#5F5E61",
    "--sjs2-palette-gray-700": "#424146",
    "--sjs2-palette-gray-750": "#36353C",
    "--sjs2-palette-gray-800": "#2D2C33",
    "--sjs2-palette-gray-900": "#1C1B20",
    "--sjs2-palette-gray-950": "#161519",
    "--sjs2-palette-gray-999": "#111014",
    "--sjs2-palette-gray-000": "#fff",
    "--sjs2-palette-red-400": "#ff6e84",
    "--sjs2-palette-red-600": "#E50A3E",
    "--sjs2-palette-red-700": "#C30935",
    "--sjs2-palette-green-400": "#15CDAB",
    "--sjs2-palette-green-600": "#19B394",
    "--sjs2-palette-green-700": "#15947A",
    "--sjs2-palette-blue-400": "#66B4FC",
    "--sjs2-palette-blue-600": "#437FD9",
    "--sjs2-palette-blue-700": "#2A6CD0",
    "--sjs2-palette-yellow-400": "#FEC64A",
    "--sjs2-palette-yellow-600": "#FF9814",
    "--sjs2-palette-yellow-700": "#F08700",
    "--sjs2-palette-violet-400": "#C36FF4",
    "--sjs2-palette-violet-600": "#A62CEC",
    "--sjs2-palette-violet-700": "#9614E1",
    "--sjs2-palette-olive-400": "#6FC648",
    "--sjs2-palette-olive-600": "#4FAF24",
    "--sjs2-palette-olive-700": "#41901E",
    "--sjs2-palette-purple-400": "#A190FA",
    "--sjs2-palette-purple-600": "#6E5BD1",
    "--sjs2-palette-purple-700": "#5640C9",
    "--sjs2-palette-indianred-400": "#F9786A",
    "--sjs2-palette-indianred-600": "#AF496B",
    "--sjs2-palette-indianred-700": "#973F5C",
    "--sjs2-is-panelless": "false",
    "--sjs2-radius-form": "var(--sjs2-radius-x100)",
    "--sjs2-radius-form-item": "var(--sjs2-radius-x050)",
    "--sjs2-radius-component-formbox": "var(--sjs2-radius-form)",
    "--sjs2-radius-component-formbox-item": "var(--sjs2-radius-form-item)",
    "--sjs2-radius-component-message": "var(--sjs2-radius-form)",
    "--sjs2-radius-component-action": "var(--sjs2-radius-form)",
    "--sjs2-radius-component-drop": "var(--sjs2-radius-x200)",
    "--sjs2-radius-component-drop-item": "var(--sjs2-radius-x100)",
    "--sjs2-radius-component-checkbox": "var(--sjs2-radius-form-item)",
    "--sjs2-radius-component-radio": "var(--sjs2-radius-round)",
    "--sjs2-radius-component-rating": "var(--sjs2-radius-round)",
    "--sjs2-radius-component-ranking": "var(--sjs2-radius-round)",
    "--sjs2-radius-component-boolean": "var(--sjs2-radius-round)",
    "--sjs2-radius-component-boolean-item": "var(--sjs2-radius-round)",
    "--sjs2-radius-component-toggle": "var(--sjs2-radius-round)",
    "--sjs2-radius-component-toggle-thumb": "var(--sjs2-radius-round)",
    "--sjs2-radius-component-track": "var(--sjs2-radius-round)",
    "--sjs2-radius-component-track-item": "var(--sjs2-radius-round)",
    "--sjs2-radius-component-track-thumb": "var(--sjs2-radius-round)",
    "--sjs2-radius-component-page": "var(--sjs2-radius-x150)",
    "--sjs2-radius-component-panel": "var(--sjs2-radius-x150)",
    "--sjs2-radius-component-panel-nested": "var(--sjs2-radius-x100)",
    "--sjs2-radius-component-modal": "var(--sjs2-radius-x300)",
    "--sjs2-radius-component-notifier": "var(--sjs2-radius-x200)",
    "--sjs2-radius-component-tooltip": "var(--sjs2-radius-x050)",
    "--sjs2-typography-font-family-text": "Open Sans",
    "--sjs2-typography-font-family-code": "DM Mono",
    "--sjs2-typography-font-family-component-input-content": "Open Sans",
    "--sjs2-typography-font-family-component-question-title": "Open Sans",
    "--sjs2-typography-font-family-component-question-description": "Open Sans",
    "--sjs2-typography-font-family-component-page-title": "Open Sans",
    "--sjs2-typography-font-family-component-page-description": "Open Sans",
    "--sjs2-typography-font-family-component-header-title": "Open Sans",
    "--sjs2-typography-font-family-component-header-description": "Open Sans",
    "--sjs2-typography-font-size-small": "var(--sjs2-font-size-x150)",
    "--sjs2-typography-font-size-default": "var(--sjs2-font-size-x200)",
    "--sjs2-typography-font-size-medium": "var(--sjs2-font-size-x300)",
    "--sjs2-typography-font-size-large": "var(--sjs2-font-size-x400)",
    "--sjs2-typography-font-size-component-input-content": "var(--sjs2-font-size-x200)",
    "--sjs2-typography-font-size-component-question-title": "var(--sjs2-font-size-x200)",
    "--sjs2-typography-font-size-component-question-description": "var(--sjs2-font-size-x200)",
    "--sjs2-typography-font-size-component-page-title": "var(--sjs2-font-size-x300)",
    "--sjs2-typography-font-size-component-page-description": "var(--sjs2-font-size-x200)",
    "--sjs2-typography-font-size-component-header-title": "var(--sjs2-font-size-x400)",
    "--sjs2-typography-font-size-component-header-description": "var(--sjs2-font-size-x300)",
    "--sjs2-typography-line-height-small": "var(--sjs2-line-height-x200)",
    "--sjs2-typography-line-height-default": "var(--sjs2-line-height-x300)",
    "--sjs2-typography-line-height-medium": "var(--sjs2-line-height-x400)",
    "--sjs2-typography-line-height-large": "var(--sjs2-line-height-x500)",
    "--sjs2-typography-line-height-component-input-content": "var(--sjs2-line-height-x300)",
    "--sjs2-typography-line-height-component-question-title": "var(--sjs2-line-height-x300)",
    "--sjs2-typography-line-height-component-question-description": "var(--sjs2-line-height-x300)",
    "--sjs2-typography-line-height-component-page-title": "var(--sjs2-line-height-x400)",
    "--sjs2-typography-line-height-component-page-description": "var(--sjs2-line-height-x300)",
    "--sjs2-typography-line-height-component-header-title": "var(--sjs2-line-height-x500)",
    "--sjs2-typography-line-height-component-header-description": "var(--sjs2-line-height-x400)",
    "--sjs2-typography-font-weight-basic": "var(--sjs2-font-weight-regular)",
    "--sjs2-typography-font-weight-strong": "var(--sjs2-font-weight-semibold)",
    "--sjs2-typography-font-weight-component-input-content": "var(--sjs2-font-weight-regular)",
    "--sjs2-typography-font-weight-component-question-title": "var(--sjs2-font-weight-semibold)",
    "--sjs2-typography-font-weight-component-question-description": "var(--sjs2-font-weight-regular)",
    "--sjs2-typography-font-weight-component-page-title": "var(--sjs2-font-weight-semibold)",
    "--sjs2-typography-font-weight-component-page-description": "var(--sjs2-font-weight-regular)",
    "--sjs2-typography-font-weight-component-header-title": "var(--sjs2-font-weight-semibold)",
    "--sjs2-typography-font-weight-component-header-description": "var(--sjs2-font-weight-regular)",
    "--sjs2-color-project-brand-400": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 1.1))",
    "--sjs2-color-project-brand-600": "#19B394",
    "--sjs2-color-project-brand-700": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 0.85))",
    "--sjs2-color-project-accent-400": "hsl(from var(--sjs2-color-project-accent-600) h s calc(l * 1.1))",
    "--sjs2-color-project-accent-600": "#19B394",
    "--sjs2-color-project-accent-700": "hsl(from var(--sjs2-color-project-accent-600) h s calc(l * 0.85))",
    "--sjs2-color-utility-body": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-utility-sheet": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-utility-a11y": "rgba(from var(--sjs2-palette-blue-400) r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-utility-scrollbar": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-utility-overlay": "rgba(from var(--sjs2-palette-gray-700) r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-utility-toolbox": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-utility-property-grid": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-utility-tabs": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-utility-surface-survey": "#1c1b200d",
    "--sjs2-color-utility-surface-survey-panelless": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-utility-surface-designer": "#EDF9F7",
    "--sjs2-color-utility-surface-presets-manager": "#1c1b200d",
    "--sjs2-color-utility-surface-dashboard": "var(--sjs2-color-utility-surface-survey)",
    "--sjs2-color-utility-surface-logic": "var(--sjs2-color-utility-surface-designer)",
    "--sjs2-color-utility-surface-json-editor": "var(--sjs2-color-utility-surface-designer)",
    "--sjs2-color-utility-surface-translations": "var(--sjs2-color-utility-surface-designer)",
    "--sjs2-color-utility-surface-embed": "var(--sjs2-color-utility-surface-designer)",
    "--sjs2-color-utility-shadow-surface-default": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-surface-hovered": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-utility-shadow-surface-pressed": "var(--sjs2-color-project-brand-600)",
    "--sjs2-color-utility-shadow-surface-focused": "var(--sjs2-color-project-brand-600)",
    "--sjs2-color-utility-shadow-surface-disabled": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-surface-dragging": "rgba(from #004C44 r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-utility-shadow-floating-default": "rgba(from #004C44 r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-basic-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-bg-basic-secondary": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-bg-basic-tertiary": "var(--sjs2-palette-gray-150)",
    "--sjs2-color-bg-basic-primary-dim": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-bg-basic-secondary-dim": "var(--sjs2-palette-gray-150)",
    "--sjs2-color-bg-basic-tertiary-dim": "var(--sjs2-palette-gray-200)",
    "--sjs2-color-bg-basic-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-neutral-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-bg-neutral-secondary": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-bg-neutral-tertiary": "rgba(from var(--sjs2-palette-gray-600) r g b / var(--sjs2-opacity-x000))",
    "--sjs2-color-bg-neutral-primary-dim": "var(--sjs2-palette-gray-700)",
    "--sjs2-color-bg-neutral-secondary-dim": "var(--sjs2-palette-gray-150)",
    "--sjs2-color-bg-neutral-tertiary-dim": "rgba(from var(--sjs2-palette-gray-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-neutral-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-brand-primary": "var(--sjs2-color-project-brand-600)",
    "--sjs2-color-bg-brand-secondary": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-brand-tertiary": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x000))",
    "--sjs2-color-bg-brand-primary-dim": "var(--sjs2-color-project-brand-700)",
    "--sjs2-color-bg-brand-secondary-dim": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-brand-tertiary-dim": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-brand-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-accent-primary": "var(--sjs2-color-project-accent-600)",
    "--sjs2-color-bg-accent-secondary": "rgba(from var(--sjs2-color-project-accent-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-accent-tertiary": "rgba(from var(--sjs2-color-project-accent-600) r g b / var(--sjs2-opacity-x000))",
    "--sjs2-color-bg-accent-primary-dim": "var(--sjs2-color-project-accent-700)",
    "--sjs2-color-bg-accent-secondary-dim": "rgba(from var(--sjs2-color-project-accent-600) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-accent-tertiary-dim": "rgba(from var(--sjs2-color-project-accent-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-accent-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-note-primary": "var(--sjs2-palette-blue-600)",
    "--sjs2-color-bg-note-secondary": "rgba(from var(--sjs2-palette-blue-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-note-tertiary": "rgba(from var(--sjs2-palette-blue-600) r g b / var(--sjs2-opacity-x000))",
    "--sjs2-color-bg-note-primary-dim": "var(--sjs2-palette-blue-700)",
    "--sjs2-color-bg-note-secondary-dim": "rgba(from var(--sjs2-palette-blue-600) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-note-tertiary-dim": "rgba(from var(--sjs2-palette-blue-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-note-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-positive-primary": "var(--sjs2-palette-green-600)",
    "--sjs2-color-bg-positive-secondary": "rgba(from var(--sjs2-palette-green-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-positive-tertiary": "rgba(from var(--sjs2-palette-green-600) r g b / var(--sjs2-opacity-x000))",
    "--sjs2-color-bg-positive-primary-dim": "var(--sjs2-palette-green-700)",
    "--sjs2-color-bg-positive-secondary-dim": "rgba(from var(--sjs2-palette-green-600) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-positive-tertiary-dim": "rgba(from var(--sjs2-palette-green-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-positive-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-warning-primary": "var(--sjs2-palette-yellow-600)",
    "--sjs2-color-bg-warning-secondary": "rgba(from var(--sjs2-palette-yellow-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-warning-tertiary": "rgba(from var(--sjs2-palette-yellow-600) r g b / var(--sjs2-opacity-x000))",
    "--sjs2-color-bg-warning-primary-dim": "var(--sjs2-palette-yellow-700)",
    "--sjs2-color-bg-warning-secondary-dim": "rgba(from var(--sjs2-palette-yellow-600) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-warning-tertiary-dim": "rgba(from var(--sjs2-palette-yellow-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-warning-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-alert-primary": "var(--sjs2-palette-red-600)",
    "--sjs2-color-bg-alert-secondary": "rgba(from var(--sjs2-palette-red-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-alert-tertiary": "rgba(from var(--sjs2-palette-red-600) r g b / var(--sjs2-opacity-x000))",
    "--sjs2-color-bg-alert-primary-dim": "var(--sjs2-palette-red-700)",
    "--sjs2-color-bg-alert-secondary-dim": "rgba(from var(--sjs2-palette-red-600) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-alert-tertiary-dim": "rgba(from var(--sjs2-palette-red-600) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-alert-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-static-1-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-bg-static-1-secondary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-static-1-primary-dim": "var(--sjs2-palette-gray-700)",
    "--sjs2-color-bg-static-1-secondary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-static-2-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-bg-static-2-secondary": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-static-2-primary-dim": "hsl(from var(--sjs2-palette-gray-100) h s calc(l * 1.1))",
    "--sjs2-color-bg-static-2-secondary-dim": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-fg-basic-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-fg-basic-primary-muted": "var(--sjs2-palette-gray-700)",
    "--sjs2-color-fg-basic-secondary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-fg-basic-tertiary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-fg-basic-primary-disabled": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-fg-neutral-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-fg-neutral-primary-muted": "var(--sjs2-palette-gray-700)",
    "--sjs2-color-fg-neutral-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-fg-neutral-primary-disabled": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-fg-brand-primary": "var(--sjs2-color-project-brand-600)",
    "--sjs2-color-fg-brand-primary-dim": "var(--sjs2-color-project-brand-700)",
    "--sjs2-color-fg-brand-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-fg-brand-primary-disabled": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-fg-accent-primary": "var(--sjs2-color-project-accent-600)",
    "--sjs2-color-fg-accent-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-fg-accent-primary-disabled": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-fg-note-primary": "var(--sjs2-palette-blue-700)",
    "--sjs2-color-fg-note-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-fg-note-primary-disabled": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-fg-positive-primary": "var(--sjs2-palette-green-600)",
    "--sjs2-color-fg-positive-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-fg-positive-primary-disabled": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-fg-warning-primary": "var(--sjs2-palette-yellow-700)",
    "--sjs2-color-fg-warning-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-fg-warning-primary-disabled": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-fg-alert-primary": "var(--sjs2-palette-red-700)",
    "--sjs2-color-fg-alert-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-fg-alert-primary-disabled": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-fg-static-1-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-fg-static-2-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-border-basic-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-border-basic-secondary": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-border-basic-secondary-overlay": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-border-neutral-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-border-neutral-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-border-brand-primary": "var(--sjs2-color-project-brand-600)",
    "--sjs2-color-border-brand-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-border-accent-primary": "var(--sjs2-color-project-accent-600)",
    "--sjs2-color-border-accent-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-border-note-primary": "var(--sjs2-palette-blue-600)",
    "--sjs2-color-border-note-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-border-positive-primary": "var(--sjs2-palette-green-600)",
    "--sjs2-color-border-positive-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-border-warning-primary": "var(--sjs2-palette-yellow-600)",
    "--sjs2-color-border-warning-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-border-alert-primary": "var(--sjs2-palette-red-600)",
    "--sjs2-color-border-alert-on-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-border-static-1-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-border-static-2-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-data-chart-bg-color-1": "#84CAD4",
    "--sjs2-color-data-chart-bg-color-2": "#3A99FB",
    "--sjs2-color-data-chart-bg-color-3": "#FF6771",
    "--sjs2-color-data-chart-bg-color-4": "#1DB496",
    "--sjs2-color-data-chart-bg-color-5": "#FFC152",
    "--sjs2-color-data-chart-bg-color-6": "#ABA1FF",
    "--sjs2-color-data-chart-bg-color-7": "#7D8CA5",
    "--sjs2-color-data-chart-bg-color-8": "#4FC46C",
    "--sjs2-color-data-chart-bg-color-9": "#E87BCB",
    "--sjs2-color-data-chart-bg-color-10": "#4E6198",
    "--sjs2-color-data-chart-bg-color-1-tinted": "rgba(from #84CAD4 r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-data-chart-bg-color-2-tinted": "rgba(from #3A99FB r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-data-chart-bg-color-3-tinted": "rgba(from #FF6771 r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-data-chart-bg-color-4-tinted": "rgba(from #1DB496 r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-data-chart-bg-color-5-tinted": "rgba(from #FFC152 r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-data-chart-bg-color-6-tinted": "rgba(from #ABA1FF r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-data-chart-bg-color-7-tinted": "rgba(from #7D8CA5 r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-data-chart-bg-color-8-tinted": "rgba(from #4FC46C r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-data-chart-bg-color-9-tinted": "rgba(from #E87BCB r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-data-chart-bg-color-10-tinted": "rgba(from #4E6198 r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-data-chart-fg-on-color-1": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-data-chart-fg-on-color-2": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-data-chart-fg-on-color-3": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-data-chart-fg-on-color-4": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-data-chart-fg-on-color-5": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-data-chart-fg-on-color-6": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-data-chart-fg-on-color-7": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-data-chart-fg-on-color-8": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-data-chart-fg-on-color-9": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-data-chart-fg-on-color-10": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-data-chart-border-color-1": "#84CAD4",
    "--sjs2-color-data-chart-border-color-2": "#3A99FB",
    "--sjs2-color-data-chart-border-color-3": "#FF6771",
    "--sjs2-color-data-chart-border-color-4": "#1DB496",
    "--sjs2-color-data-chart-border-color-5": "#FFC152",
    "--sjs2-color-data-chart-border-color-6": "#ABA1FF",
    "--sjs2-color-data-chart-border-color-7": "#7D8CA5",
    "--sjs2-color-data-chart-border-color-8": "#4FC46C",
    "--sjs2-color-data-chart-border-color-9": "#E87BCB",
    "--sjs2-color-data-chart-border-color-10": "#4E6198",
    "--sjs2-color-data-grid-fg-label": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-data-grid-border-line": "#DCDCDC",
    "--sjs2-color-data-grid-border-axis": "var(--sjs2-color-border-basic-primary)",
    "--sjs2-color-component-formbox-default-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-formbox-default-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-formbox-disabled-bg": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-component-formbox-disabled-border": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-formbox-readonly-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-formbox-readonly-border": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-formbox-focused-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-formbox-focused-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-formbox-invalid-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-formbox-invalid-border": "var(--sjs2-color-border-alert-primary)",
    "--sjs2-color-component-formbox-highlighted-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-formbox-highlighted-border": "var(--sjs2-color-border-basic-primary)",
    "--sjs2-color-component-formbox-design-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-formbox-design-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-formbox-hovered-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-formbox-hovered-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-formbox-invalid-focused-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-formbox-invalid-focused-border": "var(--sjs2-color-border-alert-primary)",
    "--sjs2-color-component-input-default-line": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-input-default-value": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-input-default-placeholder": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-input-default-label": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-input-default-limit": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-input-default-icon": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-input-default-description": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-input-disabled-line": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-input-disabled-value": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-input-disabled-placeholder": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-input-disabled-label": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-input-disabled-limit": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-input-disabled-icon": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-input-disabled-description": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-buttongroup-item-false-default-bg": "rgba(from var(--sjs2-color-bg-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-false-default-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-false-default-value": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-buttongroup-item-false-disabled-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-false-disabled-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-false-disabled-value": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-buttongroup-item-false-readonly-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-false-readonly-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-false-readonly-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-buttongroup-item-false-focused-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-buttongroup-item-false-focused-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-buttongroup-item-false-focused-value": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-false-hovered-bg": "var(--sjs2-color-bg-basic-secondary-dim)",
    "--sjs2-color-component-buttongroup-item-false-hovered-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-buttongroup-item-false-hovered-value": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-true-default-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-true-default-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-buttongroup-item-true-default-value": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-buttongroup-item-true-disabled-bg": "var(--sjs2-color-bg-basic-primary-dim)",
    "--sjs2-color-component-buttongroup-item-true-disabled-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-true-disabled-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-buttongroup-item-true-readonly-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-true-readonly-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-buttongroup-item-true-readonly-value": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-true-focused-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-true-focused-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-buttongroup-item-true-focused-value": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-formbox-action-default-bg": "var(--sjs2-color-bg-neutral-tertiary)",
    "--sjs2-color-component-formbox-action-default-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-formbox-action-default-icon": "var(--sjs2-color-fg-neutral-primary-muted)",
    "--sjs2-color-component-formbox-action-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-formbox-action-hovered-bg": "var(--sjs2-color-bg-neutral-tertiary-dim)",
    "--sjs2-color-component-formbox-action-hovered-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-formbox-action-hovered-icon": "var(--sjs2-color-fg-neutral-primary-muted)",
    "--sjs2-color-component-formbox-action-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-formbox-action-pressed-bg": "var(--sjs2-color-bg-neutral-tertiary-dim)",
    "--sjs2-color-component-formbox-action-pressed-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-formbox-action-pressed-icon": "var(--sjs2-color-fg-neutral-primary-muted)",
    "--sjs2-color-component-formbox-action-pressed-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-formbox-action-disabled-bg": "rgba(from var(--sjs2-color-bg-neutral-tertiary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-formbox-action-disabled-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-formbox-action-disabled-icon": "var(--sjs2-color-fg-neutral-primary-disabled)",
    "--sjs2-color-component-formbox-action-disabled-label": "var(--sjs2-color-fg-neutral-primary-disabled)",
    "--sjs2-color-component-action-alert-primary-default-bg": "var(--sjs2-color-bg-alert-primary)",
    "--sjs2-color-component-action-alert-primary-default-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-primary-default-icon": "var(--sjs2-color-fg-alert-on-primary)",
    "--sjs2-color-component-action-alert-primary-default-label": "var(--sjs2-color-fg-alert-on-primary)",
    "--sjs2-color-component-action-alert-primary-hovered-bg": "var(--sjs2-color-bg-alert-primary-dim)",
    "--sjs2-color-component-action-alert-primary-hovered-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-primary-hovered-icon": "var(--sjs2-color-fg-alert-on-primary)",
    "--sjs2-color-component-action-alert-primary-hovered-label": "var(--sjs2-color-fg-alert-on-primary)",
    "--sjs2-color-component-action-alert-primary-pressed-bg": "var(--sjs2-color-bg-alert-primary)",
    "--sjs2-color-component-action-alert-primary-pressed-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-primary-pressed-icon": "var(--sjs2-color-fg-alert-on-primary)",
    "--sjs2-color-component-action-alert-primary-pressed-label": "var(--sjs2-color-fg-alert-on-primary)",
    "--sjs2-color-component-action-alert-primary-disabled-bg": "var(--sjs2-color-bg-alert-primary-disabled)",
    "--sjs2-color-component-action-alert-primary-disabled-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-primary-disabled-icon": "var(--sjs2-color-fg-alert-primary-disabled)",
    "--sjs2-color-component-action-alert-primary-disabled-label": "var(--sjs2-color-fg-alert-primary-disabled)",
    "--sjs2-color-component-action-alert-secondary-default-bg": "var(--sjs2-color-bg-alert-secondary)",
    "--sjs2-color-component-action-alert-secondary-default-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-secondary-default-icon": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-secondary-default-label": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-secondary-hovered-bg": "var(--sjs2-color-bg-alert-secondary-dim)",
    "--sjs2-color-component-action-alert-secondary-hovered-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-secondary-hovered-icon": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-secondary-hovered-label": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-secondary-pressed-bg": "var(--sjs2-color-bg-alert-secondary)",
    "--sjs2-color-component-action-alert-secondary-pressed-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-secondary-pressed-icon": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-secondary-pressed-label": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-secondary-disabled-bg": "var(--sjs2-color-bg-alert-primary-disabled)",
    "--sjs2-color-component-action-alert-secondary-disabled-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-secondary-disabled-icon": "var(--sjs2-color-fg-alert-primary-disabled)",
    "--sjs2-color-component-action-alert-secondary-disabled-label": "var(--sjs2-color-fg-alert-primary-disabled)",
    "--sjs2-color-component-action-alert-tertiary-default-bg": "var(--sjs2-color-bg-alert-tertiary)",
    "--sjs2-color-component-action-alert-tertiary-default-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-tertiary-default-icon": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-tertiary-default-label": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-tertiary-hovered-bg": "var(--sjs2-color-bg-alert-tertiary-dim)",
    "--sjs2-color-component-action-alert-tertiary-hovered-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-tertiary-hovered-icon": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-tertiary-hovered-label": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-tertiary-pressed-bg": "var(--sjs2-color-bg-alert-tertiary-dim)",
    "--sjs2-color-component-action-alert-tertiary-pressed-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-tertiary-pressed-icon": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-tertiary-pressed-label": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-action-alert-tertiary-disabled-bg": "rgba(from var(--sjs2-color-bg-alert-tertiary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-tertiary-disabled-border": "rgba(from var(--sjs2-color-border-alert-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-alert-tertiary-disabled-icon": "var(--sjs2-color-fg-alert-primary-disabled)",
    "--sjs2-color-component-action-alert-tertiary-disabled-label": "var(--sjs2-color-fg-alert-primary-disabled)",
    "--sjs2-color-component-action-brand-primary-default-bg": "var(--sjs2-color-bg-brand-primary)",
    "--sjs2-color-component-action-brand-primary-default-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-primary-default-icon": "var(--sjs2-color-fg-brand-on-primary)",
    "--sjs2-color-component-action-brand-primary-default-label": "var(--sjs2-color-fg-brand-on-primary)",
    "--sjs2-color-component-action-brand-primary-hovered-bg": "var(--sjs2-color-bg-brand-primary-dim)",
    "--sjs2-color-component-action-brand-primary-hovered-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-primary-hovered-icon": "var(--sjs2-color-fg-brand-on-primary)",
    "--sjs2-color-component-action-brand-primary-hovered-label": "var(--sjs2-color-fg-brand-on-primary)",
    "--sjs2-color-component-action-brand-primary-pressed-bg": "var(--sjs2-color-bg-brand-primary)",
    "--sjs2-color-component-action-brand-primary-pressed-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-primary-pressed-icon": "var(--sjs2-color-fg-brand-on-primary)",
    "--sjs2-color-component-action-brand-primary-pressed-label": "var(--sjs2-color-fg-brand-on-primary)",
    "--sjs2-color-component-action-brand-primary-disabled-bg": "var(--sjs2-color-bg-brand-primary-disabled)",
    "--sjs2-color-component-action-brand-primary-disabled-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-primary-disabled-icon": "var(--sjs2-color-fg-brand-primary-disabled)",
    "--sjs2-color-component-action-brand-primary-disabled-label": "var(--sjs2-color-fg-brand-primary-disabled)",
    "--sjs2-color-component-action-brand-secondary-default-bg": "var(--sjs2-color-bg-brand-secondary)",
    "--sjs2-color-component-action-brand-secondary-default-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-secondary-default-icon": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-secondary-default-label": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-secondary-hovered-bg": "var(--sjs2-color-bg-brand-secondary-dim)",
    "--sjs2-color-component-action-brand-secondary-hovered-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-secondary-hovered-icon": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-secondary-hovered-label": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-secondary-pressed-bg": "var(--sjs2-color-bg-brand-secondary)",
    "--sjs2-color-component-action-brand-secondary-pressed-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-secondary-pressed-icon": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-secondary-pressed-label": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-secondary-disabled-bg": "var(--sjs2-color-bg-brand-primary-disabled)",
    "--sjs2-color-component-action-brand-secondary-disabled-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-secondary-disabled-icon": "var(--sjs2-color-fg-brand-primary-disabled)",
    "--sjs2-color-component-action-brand-secondary-disabled-label": "var(--sjs2-color-fg-brand-primary-disabled)",
    "--sjs2-color-component-action-brand-tertiary-default-bg": "var(--sjs2-color-bg-brand-tertiary)",
    "--sjs2-color-component-action-brand-tertiary-default-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-tertiary-default-icon": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-tertiary-default-label": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-tertiary-hovered-bg": "var(--sjs2-color-bg-brand-tertiary-dim)",
    "--sjs2-color-component-action-brand-tertiary-hovered-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-tertiary-hovered-icon": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-tertiary-hovered-label": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-tertiary-pressed-bg": "var(--sjs2-color-bg-brand-tertiary-dim)",
    "--sjs2-color-component-action-brand-tertiary-pressed-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-tertiary-pressed-icon": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-tertiary-pressed-label": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-action-brand-tertiary-disabled-bg": "rgba(from var(--sjs2-color-bg-brand-tertiary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-tertiary-disabled-border": "rgba(from var(--sjs2-color-border-brand-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-brand-tertiary-disabled-icon": "var(--sjs2-color-fg-brand-primary-disabled)",
    "--sjs2-color-component-action-brand-tertiary-disabled-label": "var(--sjs2-color-fg-brand-primary-disabled)",
    "--sjs2-color-component-action-accent-primary-default-bg": "var(--sjs2-color-bg-accent-primary)",
    "--sjs2-color-component-action-accent-primary-default-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-primary-default-icon": "var(--sjs2-color-fg-accent-on-primary)",
    "--sjs2-color-component-action-accent-primary-default-label": "var(--sjs2-color-fg-accent-on-primary)",
    "--sjs2-color-component-action-accent-primary-hovered-bg": "var(--sjs2-color-bg-accent-primary-dim)",
    "--sjs2-color-component-action-accent-primary-hovered-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-primary-hovered-icon": "var(--sjs2-color-fg-accent-on-primary)",
    "--sjs2-color-component-action-accent-primary-hovered-label": "var(--sjs2-color-fg-accent-on-primary)",
    "--sjs2-color-component-action-accent-primary-pressed-bg": "var(--sjs2-color-bg-accent-primary)",
    "--sjs2-color-component-action-accent-primary-pressed-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-primary-pressed-icon": "var(--sjs2-color-fg-accent-on-primary)",
    "--sjs2-color-component-action-accent-primary-pressed-label": "var(--sjs2-color-fg-accent-on-primary)",
    "--sjs2-color-component-action-accent-primary-disabled-bg": "var(--sjs2-color-bg-accent-primary-disabled)",
    "--sjs2-color-component-action-accent-primary-disabled-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-primary-disabled-icon": "var(--sjs2-color-fg-accent-primary-disabled)",
    "--sjs2-color-component-action-accent-primary-disabled-label": "var(--sjs2-color-fg-accent-primary-disabled)",
    "--sjs2-color-component-action-accent-secondary-default-bg": "var(--sjs2-color-bg-accent-secondary)",
    "--sjs2-color-component-action-accent-secondary-default-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-secondary-default-icon": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-secondary-default-label": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-secondary-hovered-bg": "var(--sjs2-color-bg-accent-secondary-dim)",
    "--sjs2-color-component-action-accent-secondary-hovered-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-secondary-hovered-icon": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-secondary-hovered-label": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-secondary-pressed-bg": "var(--sjs2-color-bg-accent-secondary)",
    "--sjs2-color-component-action-accent-secondary-pressed-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-secondary-pressed-icon": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-secondary-pressed-label": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-secondary-disabled-bg": "var(--sjs2-color-bg-accent-primary-disabled)",
    "--sjs2-color-component-action-accent-secondary-disabled-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-secondary-disabled-icon": "var(--sjs2-color-fg-accent-primary-disabled)",
    "--sjs2-color-component-action-accent-secondary-disabled-label": "var(--sjs2-color-fg-accent-primary-disabled)",
    "--sjs2-color-component-action-accent-tertiary-default-bg": "var(--sjs2-color-bg-accent-tertiary)",
    "--sjs2-color-component-action-accent-tertiary-default-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-tertiary-default-icon": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-tertiary-default-label": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-tertiary-hovered-bg": "var(--sjs2-color-bg-accent-tertiary-dim)",
    "--sjs2-color-component-action-accent-tertiary-hovered-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-tertiary-hovered-icon": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-tertiary-hovered-label": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-tertiary-pressed-bg": "var(--sjs2-color-bg-accent-tertiary-dim)",
    "--sjs2-color-component-action-accent-tertiary-pressed-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-tertiary-pressed-icon": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-tertiary-pressed-label": "var(--sjs2-color-fg-accent-primary)",
    "--sjs2-color-component-action-accent-tertiary-disabled-bg": "rgba(from var(--sjs2-color-bg-accent-tertiary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-tertiary-disabled-border": "rgba(from var(--sjs2-color-border-accent-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-accent-tertiary-disabled-icon": "var(--sjs2-color-fg-accent-primary-disabled)",
    "--sjs2-color-component-action-accent-tertiary-disabled-label": "var(--sjs2-color-fg-accent-primary-disabled)",
    "--sjs2-color-component-action-neutral-primary-default-bg": "var(--sjs2-color-bg-neutral-primary)",
    "--sjs2-color-component-action-neutral-primary-default-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-primary-default-icon": "var(--sjs2-color-fg-neutral-on-primary)",
    "--sjs2-color-component-action-neutral-primary-default-label": "var(--sjs2-color-fg-neutral-on-primary)",
    "--sjs2-color-component-action-neutral-primary-hovered-bg": "var(--sjs2-color-bg-neutral-primary-dim)",
    "--sjs2-color-component-action-neutral-primary-hovered-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-primary-hovered-icon": "var(--sjs2-color-fg-neutral-on-primary)",
    "--sjs2-color-component-action-neutral-primary-hovered-label": "var(--sjs2-color-fg-neutral-on-primary)",
    "--sjs2-color-component-action-neutral-primary-pressed-bg": "var(--sjs2-color-bg-neutral-primary)",
    "--sjs2-color-component-action-neutral-primary-pressed-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-primary-pressed-icon": "var(--sjs2-color-fg-neutral-on-primary)",
    "--sjs2-color-component-action-neutral-primary-pressed-label": "var(--sjs2-color-fg-neutral-on-primary)",
    "--sjs2-color-component-action-neutral-primary-disabled-bg": "var(--sjs2-color-bg-neutral-primary-disabled)",
    "--sjs2-color-component-action-neutral-primary-disabled-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-primary-disabled-icon": "var(--sjs2-color-fg-neutral-primary-disabled)",
    "--sjs2-color-component-action-neutral-primary-disabled-label": "var(--sjs2-color-fg-neutral-primary-disabled)",
    "--sjs2-color-component-action-neutral-secondary-default-bg": "var(--sjs2-color-bg-neutral-secondary)",
    "--sjs2-color-component-action-neutral-secondary-default-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-secondary-default-icon": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-hovered-bg": "var(--sjs2-color-bg-neutral-secondary-dim)",
    "--sjs2-color-component-action-neutral-secondary-hovered-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-secondary-hovered-icon": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-pressed-bg": "var(--sjs2-color-bg-neutral-secondary)",
    "--sjs2-color-component-action-neutral-secondary-pressed-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-secondary-pressed-icon": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-pressed-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-disabled-bg": "var(--sjs2-color-bg-neutral-primary-disabled)",
    "--sjs2-color-component-action-neutral-secondary-disabled-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-secondary-disabled-icon": "var(--sjs2-color-fg-neutral-primary-disabled)",
    "--sjs2-color-component-action-neutral-secondary-disabled-label": "var(--sjs2-color-fg-neutral-primary-disabled)",
    "--sjs2-color-component-action-neutral-tertiary-default-bg": "var(--sjs2-color-bg-neutral-tertiary)",
    "--sjs2-color-component-action-neutral-tertiary-default-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-tertiary-default-icon": "var(--sjs2-color-fg-neutral-primary-muted)",
    "--sjs2-color-component-action-neutral-tertiary-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-hovered-bg": "var(--sjs2-color-bg-neutral-tertiary-dim)",
    "--sjs2-color-component-action-neutral-tertiary-hovered-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-tertiary-hovered-icon": "var(--sjs2-color-fg-neutral-primary-muted)",
    "--sjs2-color-component-action-neutral-tertiary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-pressed-bg": "var(--sjs2-color-bg-neutral-tertiary-dim)",
    "--sjs2-color-component-action-neutral-tertiary-pressed-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-tertiary-pressed-icon": "var(--sjs2-color-fg-neutral-primary-muted)",
    "--sjs2-color-component-action-neutral-tertiary-pressed-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-disabled-bg": "rgba(from var(--sjs2-color-bg-neutral-tertiary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-tertiary-disabled-border": "rgba(from var(--sjs2-color-border-neutral-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-action-neutral-tertiary-disabled-icon": "var(--sjs2-color-fg-neutral-primary-disabled)",
    "--sjs2-color-component-action-neutral-tertiary-disabled-label": "var(--sjs2-color-fg-neutral-primary-disabled)",
    "--sjs2-color-component-check-false-default-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-check-false-default-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-check-false-disabled-bg": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-component-check-false-disabled-border": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-check-false-readonly-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-check-false-readonly-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-check-false-focused-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-check-false-focused-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-check-false-hovered-bg": "var(--sjs2-color-bg-basic-secondary-dim)",
    "--sjs2-color-component-check-false-hovered-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-check-false-design-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-check-false-design-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-check-true-default-bg": "var(--sjs2-color-bg-brand-primary)",
    "--sjs2-color-component-check-true-default-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-check-true-default-icon": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-check-true-disabled-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-check-true-disabled-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-check-true-disabled-icon": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-check-true-readonly-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-check-true-readonly-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-check-true-readonly-icon": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-check-true-focused-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-check-true-focused-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-check-true-focused-icon": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-check-true-hovered-bg": "var(--sjs2-color-bg-brand-primary-dim)",
    "--sjs2-color-component-check-true-hovered-border": "var(--sjs2-color-bg-brand-primary-dim)",
    "--sjs2-color-component-check-true-hovered-icon": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-false-default-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-toggle-false-default-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-toggle-false-default-thumb": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-toggle-false-disabled-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-toggle-false-disabled-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-toggle-false-disabled-thumb": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-toggle-false-readonly-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-toggle-false-readonly-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-toggle-false-readonly-thumb": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-toggle-false-focused-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-toggle-false-focused-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-toggle-false-focused-thumb": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-toggle-false-hovered-bg": "var(--sjs2-color-bg-basic-secondary-dim)",
    "--sjs2-color-component-toggle-false-hovered-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-toggle-false-hovered-thumb": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-toggle-true-default-bg": "var(--sjs2-color-bg-brand-primary)",
    "--sjs2-color-component-toggle-true-default-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-toggle-true-default-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-true-disabled-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-toggle-true-disabled-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-toggle-true-disabled-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-true-readonly-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-toggle-true-readonly-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-toggle-true-readonly-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-true-focused-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-toggle-true-focused-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-toggle-true-focused-thumb": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-toggle-true-hovered-bg": "var(--sjs2-color-bg-brand-primary-dim)",
    "--sjs2-color-component-toggle-true-hovered-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-toggle-true-hovered-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-message-error-bg": "var(--sjs2-color-bg-alert-secondary)",
    "--sjs2-color-component-message-error-icon": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-message-error-text": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-message-info-bg": "var(--sjs2-color-bg-note-secondary)",
    "--sjs2-color-component-message-info-icon": "var(--sjs2-color-fg-note-primary)",
    "--sjs2-color-component-message-info-text": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-track-default-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-track-default-fg": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-track-default-thumb": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-track-default-dot": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-track-default-thumb-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-track-disabled-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-track-disabled-fg": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-track-disabled-thumb": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-track-disabled-dot": "var(--sjs2-color-fg-basic-primary-disabled)",
    "--sjs2-color-component-track-disabled-thumb-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-track-readonly-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-track-readonly-fg": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-track-readonly-thumb": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-track-readonly-dot": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-track-readonly-thumb-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-track-focused-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-track-focused-fg": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-track-focused-thumb": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-track-focused-dot": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-track-focused-thumb-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-track-invalid-bg": "var(--sjs2-color-bg-alert-secondary)",
    "--sjs2-color-component-track-invalid-fg": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-track-invalid-thumb": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-track-invalid-dot": "var(--sjs2-color-fg-alert-primary)",
    "--sjs2-color-component-track-invalid-thumb-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-track-design-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-track-design-fg": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-track-design-thumb": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-track-design-dot": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-track-design-thumb-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-panel-default-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-panel-default-border": "var(--sjs2-color-utility-shadow-surface-default)",
    "--sjs2-color-component-panel-hovered-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-panel-hovered-border": "var(--sjs2-color-utility-shadow-surface-hovered)",
    "--sjs2-color-component-panel-pressed-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-panel-pressed-border": "var(--sjs2-color-utility-shadow-surface-pressed)",
    "--sjs2-color-component-panel-focused-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-panel-focused-border": "var(--sjs2-color-utility-shadow-surface-focused)",
    "--sjs2-color-component-panel-disabled-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-panel-disabled-border": "var(--sjs2-color-utility-shadow-surface-disabled)",
    "--sjs2-color-component-panel-dragging-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-panel-dragging-border": "var(--sjs2-color-utility-shadow-surface-dragging)",
    "--sjs2-color-component-question-default-title": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-question-default-title-placeholder": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-question-default-description": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-question-default-description-placeholder": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-page-default-title": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-page-default-title-placeholder": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-page-default-description": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-page-default-description-placeholder": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-header-default-title": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-header-default-title-placeholder": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-header-default-description": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-header-default-description-placeholder": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-header-default-bg": "transparent",
    "--sjs2-color-component-boolean-item-false-default-bg": "rgba(from var(--sjs2-color-bg-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-boolean-item-false-default-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-boolean-item-false-default-value": "var(--sjs2-color-fg-basic-secondary)",
    "--sjs2-color-component-boolean-item-false-disabled-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-boolean-item-false-disabled-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-boolean-item-false-disabled-value": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-boolean-item-false-readonly-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-boolean-item-false-readonly-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-boolean-item-false-readonly-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-boolean-item-false-hovered-bg": "var(--sjs2-color-bg-basic-secondary-dim)",
    "--sjs2-color-component-boolean-item-false-hovered-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-boolean-item-false-hovered-value": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-boolean-item-true-default-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-boolean-item-true-default-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-boolean-item-true-default-value": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-boolean-item-true-disabled-bg": "var(--sjs2-color-bg-basic-primary-dim)",
    "--sjs2-color-component-boolean-item-true-disabled-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-boolean-item-true-disabled-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-boolean-item-true-readonly-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-boolean-item-true-readonly-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-boolean-item-true-readonly-value": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-boolean-default-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-boolean-default-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-boolean-disabled-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-boolean-disabled-border": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-boolean-readonly-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-boolean-readonly-border": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-boolean-invalid-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-boolean-invalid-border": "var(--sjs2-color-border-alert-primary)",
    "--sjs2-color-component-boolean-highlighted-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-boolean-highlighted-border": "var(--sjs2-color-border-basic-primary)",
    "--sjs2-color-component-boolean-design-bg": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-boolean-design-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-tagbox-item-default-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-tagbox-item-default-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-tagbox-item-default-label": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-tagbox-item-default-mask-stop-1": "var(--sjs2-color-component-tagbox-item-default-bg)",
    "--sjs2-color-component-tagbox-item-default-mask-stop-2": "rgba(from var(--sjs2-color-bg-basic-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-tagbox-item-hovered-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-tagbox-item-hovered-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-tagbox-item-hovered-label": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-tagbox-item-hovered-mask-stop-1": "var(--sjs2-color-component-tagbox-item-hovered-bg)",
    "--sjs2-color-component-tagbox-item-hovered-mask-stop-2": "rgba(from var(--sjs2-color-bg-basic-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-tagbox-item-readonly-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-tagbox-item-readonly-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-tagbox-item-readonly-label": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-tagbox-item-disabled-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-tagbox-item-disabled-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-tagbox-item-disabled-label": "var(--sjs2-color-fg-basic-primary-disabled)",
    "--sjs2-color-component-tagbox-item-action-default-bg": "var(--sjs2-color-bg-neutral-secondary)",
    "--sjs2-color-component-tagbox-item-action-default-icon": "var(--sjs2-color-fg-neutral-primary-muted)",
    "--sjs2-color-component-tagbox-item-action-hovered-bg": "var(--sjs2-color-bg-neutral-secondary-dim)",
    "--sjs2-color-component-tagbox-item-action-hovered-icon": "var(--sjs2-color-fg-neutral-primary-muted)",
    "--sjs2-color-component-tagbox-item-action-pressed-bg": "var(--sjs2-color-bg-neutral-secondary)",
    "--sjs2-color-component-tagbox-item-action-pressed-icon": "var(--sjs2-color-fg-neutral-primary-muted)",
    "--sjs2-opacity-visible": "var(--sjs2-opacity-x100)",
    "--sjs2-opacity-hovered": "var(--sjs2-opacity-x100)",
    "--sjs2-opacity-pressed": "var(--sjs2-opacity-x100)",
    "--sjs2-opacity-disabled": "var(--sjs2-opacity-x025)",
    "--sjs2-opacity-hidden": "var(--sjs2-opacity-x000)",
    "--sjs2-border-width-default": "var(--sjs2-border-width-x100)",
    "--sjs2-border-width-focused": "var(--sjs2-border-width-x200)",
    "--sjs2-border-width-a11y": "var(--sjs2-border-width-x400)",
    "--sjs2-border-spread-form-default": "0px",
    "--sjs2-border-spread-form-hovered": "0px",
    "--sjs2-border-spread-form-pressed": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-form-focused": "var(--sjs2-border-width-x200)",
    "--sjs2-border-spread-form-highlighted": "var(--sjs2-border-width-x200)",
    "--sjs2-border-spread-form-disabled": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-form-invalid": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-form-invalid-focused": "var(--sjs2-border-width-x200)",
    "--sjs2-border-spread-form-readonly": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-form-design": "0px",
    "--sjs2-border-spread-trigger-default": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-trigger-hovered": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-trigger-pressed": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-trigger-focused": "var(--sjs2-border-width-x200)",
    "--sjs2-border-spread-trigger-disabled": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-trigger-design": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-surface-default": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-surface-hovered": "var(--sjs2-border-width-x200)",
    "--sjs2-border-spread-surface-pressed": "var(--sjs2-border-width-x200)",
    "--sjs2-border-spread-surface-focused": "var(--sjs2-border-width-x200)",
    "--sjs2-border-spread-surface-disabled": "var(--sjs2-border-width-x100)",
    "--sjs2-border-spread-surface-dragging": "4px",
    "--sjs2-border-spread-floating-default": "0px",
    "--sjs2-border-blur-form-default": "2px",
    "--sjs2-border-blur-form-hovered": "2px",
    "--sjs2-border-blur-form-pressed": "0px",
    "--sjs2-border-blur-form-focused": "0px",
    "--sjs2-border-blur-form-highlighted": "0px",
    "--sjs2-border-blur-form-disabled": "0px",
    "--sjs2-border-blur-form-invalid": "0px",
    "--sjs2-border-blur-form-invalid-focused": "0px",
    "--sjs2-border-blur-form-readonly": "0px",
    "--sjs2-border-blur-form-design": "2px",
    "--sjs2-border-blur-trigger-default": "2px",
    "--sjs2-border-blur-trigger-hovered": "2px",
    "--sjs2-border-blur-trigger-pressed": "0px",
    "--sjs2-border-blur-trigger-focused": "0px",
    "--sjs2-border-blur-trigger-disabled": "0px",
    "--sjs2-border-blur-trigger-design": "2px",
    "--sjs2-border-blur-surface-default": "4px",
    "--sjs2-border-blur-surface-hovered": "0px",
    "--sjs2-border-blur-surface-pressed": "0px",
    "--sjs2-border-blur-surface-focused": "0px",
    "--sjs2-border-blur-surface-disabled": "0px",
    "--sjs2-border-blur-surface-dragging": "12px",
    "--sjs2-border-blur-floating-default": "20px",
    "--sjs2-border-offset-x-form-default": "0px",
    "--sjs2-border-offset-x-form-hovered": "0px",
    "--sjs2-border-offset-x-form-pressed": "0px",
    "--sjs2-border-offset-x-form-focused": "0px",
    "--sjs2-border-offset-x-form-highlighted": "0px",
    "--sjs2-border-offset-x-form-disabled": "0px",
    "--sjs2-border-offset-x-form-invalid": "0px",
    "--sjs2-border-offset-x-form-invalid-focused": "0px",
    "--sjs2-border-offset-x-form-readonly": "0px",
    "--sjs2-border-offset-x-form-design": "0px",
    "--sjs2-border-offset-x-trigger-default": "0px",
    "--sjs2-border-offset-x-trigger-hovered": "0px",
    "--sjs2-border-offset-x-trigger-pressed": "0px",
    "--sjs2-border-offset-x-trigger-focused": "0px",
    "--sjs2-border-offset-x-trigger-disabled": "0px",
    "--sjs2-border-offset-x-trigger-design": "0px",
    "--sjs2-border-offset-x-surface-default": "0px",
    "--sjs2-border-offset-x-surface-hovered": "0px",
    "--sjs2-border-offset-x-surface-pressed": "0px",
    "--sjs2-border-offset-x-surface-focused": "0px",
    "--sjs2-border-offset-x-surface-disabled": "0px",
    "--sjs2-border-offset-x-surface-dragging": "0px",
    "--sjs2-border-offset-x-floating-default": "0px",
    "--sjs2-border-offset-y-form-default": "1px",
    "--sjs2-border-offset-y-form-hovered": "1px",
    "--sjs2-border-offset-y-form-pressed": "0px",
    "--sjs2-border-offset-y-form-focused": "0px",
    "--sjs2-border-offset-y-form-highlighted": "0px",
    "--sjs2-border-offset-y-form-disabled": "0px",
    "--sjs2-border-offset-y-form-invalid": "0px",
    "--sjs2-border-offset-y-form-invalid-focused": "0px",
    "--sjs2-border-offset-y-form-readonly": "0px",
    "--sjs2-border-offset-y-form-design": "1px",
    "--sjs2-border-offset-y-trigger-default": "1px",
    "--sjs2-border-offset-y-trigger-hovered": "1px",
    "--sjs2-border-offset-y-trigger-pressed": "0px",
    "--sjs2-border-offset-y-trigger-focused": "0px",
    "--sjs2-border-offset-y-trigger-disabled": "0px",
    "--sjs2-border-offset-y-trigger-design": "1px",
    "--sjs2-border-offset-y-surface-default": "2px",
    "--sjs2-border-offset-y-surface-hovered": "0px",
    "--sjs2-border-offset-y-surface-pressed": "0px",
    "--sjs2-border-offset-y-surface-focused": "0px",
    "--sjs2-border-offset-y-surface-disabled": "0px",
    "--sjs2-border-offset-y-surface-dragging": "6px",
    "--sjs2-border-offset-y-floating-default": "6px",
    "--sjs2-border-effect-component-formbox-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-formbox-default-border)",
    "--sjs2-border-effect-component-formbox-hovered": "inset var(--sjs2-border-offset-x-form-hovered) var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-spread-form-hovered) var(--sjs2-color-component-formbox-hovered-border)",
    "--sjs2-border-effect-component-formbox-focused": "inset var(--sjs2-border-offset-x-form-focused) var(--sjs2-border-offset-y-form-focused) var(--sjs2-border-blur-form-focused) var(--sjs2-border-spread-form-focused) var(--sjs2-color-component-formbox-focused-border)",
    "--sjs2-border-effect-component-formbox-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-spread-form-disabled) var(--sjs2-color-component-formbox-disabled-border)",
    "--sjs2-border-effect-component-formbox-invalid": "inset var(--sjs2-border-offset-x-form-invalid) var(--sjs2-border-offset-y-form-invalid) var(--sjs2-border-blur-form-invalid) var(--sjs2-border-spread-form-invalid) var(--sjs2-color-component-formbox-invalid-border)",
    "--sjs2-border-effect-component-formbox-invalid-focused": "inset var(--sjs2-border-offset-x-form-invalid-focused) var(--sjs2-border-offset-y-form-invalid-focused) var(--sjs2-border-blur-form-invalid-focused) var(--sjs2-border-spread-form-invalid-focused) var(--sjs2-color-component-formbox-invalid-focused-border)",
    "--sjs2-border-effect-component-formbox-highlighted": "inset var(--sjs2-border-offset-x-form-highlighted) var(--sjs2-border-offset-y-form-highlighted) var(--sjs2-border-blur-form-highlighted) var(--sjs2-border-spread-form-highlighted) var(--sjs2-color-component-formbox-highlighted-border)",
    "--sjs2-border-effect-component-formbox-readonly": "inset var(--sjs2-border-offset-x-form-readonly) var(--sjs2-border-offset-y-form-readonly) var(--sjs2-border-blur-form-readonly) var(--sjs2-border-spread-form-readonly) var(--sjs2-color-component-formbox-readonly-border)",
    "--sjs2-border-effect-component-formbox-design": "inset var(--sjs2-border-offset-x-form-design) var(--sjs2-border-offset-y-form-design) var(--sjs2-border-blur-form-design) var(--sjs2-border-spread-form-design) var(--sjs2-color-component-formbox-design-border)",
    "--sjs2-border-effect-component-check-false-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-check-false-default-border)",
    "--sjs2-border-effect-component-check-false-hovered": "inset var(--sjs2-border-offset-x-form-hovered) var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-spread-form-hovered) var(--sjs2-color-component-check-false-hovered-border)",
    "--sjs2-border-effect-component-check-false-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-spread-form-disabled) var(--sjs2-color-component-check-false-disabled-border)",
    "--sjs2-border-effect-component-check-false-design": "inset var(--sjs2-border-offset-x-form-design) var(--sjs2-border-offset-y-form-design) var(--sjs2-border-blur-form-design) var(--sjs2-border-spread-form-design) var(--sjs2-color-component-check-false-design-border)",
    "--sjs2-border-effect-component-check-true-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-check-true-default-border)",
    "--sjs2-border-effect-component-check-true-hovered": "inset var(--sjs2-border-offset-x-form-hovered) var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-spread-form-hovered) var(--sjs2-color-component-check-true-hovered-border)",
    "--sjs2-border-effect-component-check-true-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-spread-form-disabled) var(--sjs2-color-component-check-true-disabled-border)",
    "--sjs2-border-effect-component-toggle-false-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-toggle-false-default-border)",
    "--sjs2-border-effect-component-toggle-false-hovered": "inset var(--sjs2-border-offset-x-form-hovered) var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-spread-form-hovered) var(--sjs2-color-component-toggle-false-hovered-border)",
    "--sjs2-border-effect-component-toggle-false-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-spread-form-disabled) var(--sjs2-color-component-toggle-false-disabled-border)",
    "--sjs2-border-effect-component-toggle-true-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-toggle-true-default-border)",
    "--sjs2-border-effect-component-toggle-true-hovered": "inset var(--sjs2-border-offset-x-form-hovered) var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-spread-form-hovered) var(--sjs2-color-component-toggle-true-hovered-border)",
    "--sjs2-border-effect-component-toggle-true-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-spread-form-disabled) var(--sjs2-color-component-toggle-true-disabled-border)",
    "--sjs2-border-effect-surface-default": "var(--sjs2-border-offset-x-surface-default) var(--sjs2-border-offset-y-surface-default) var(--sjs2-border-blur-surface-default) var(--sjs2-border-spread-surface-default) var(--sjs2-color-utility-shadow-surface-default)",
    "--sjs2-border-effect-surface-hovered": "var(--sjs2-border-offset-x-surface-hovered) var(--sjs2-border-offset-y-surface-hovered) var(--sjs2-border-blur-surface-hovered) var(--sjs2-border-spread-surface-hovered) var(--sjs2-color-utility-shadow-surface-hovered)",
    "--sjs2-border-effect-surface-pressed": "var(--sjs2-border-offset-x-surface-pressed) var(--sjs2-border-offset-y-surface-pressed) var(--sjs2-border-blur-surface-pressed) var(--sjs2-border-spread-surface-pressed) var(--sjs2-color-utility-shadow-surface-pressed)",
    "--sjs2-border-effect-surface-focused": "var(--sjs2-border-offset-x-surface-focused) var(--sjs2-border-offset-y-surface-focused) var(--sjs2-border-blur-surface-focused) var(--sjs2-border-spread-surface-focused) var(--sjs2-color-utility-shadow-surface-focused)",
    "--sjs2-border-effect-surface-disabled": "var(--sjs2-border-offset-x-surface-disabled) var(--sjs2-border-offset-y-surface-disabled) var(--sjs2-border-blur-surface-disabled) var(--sjs2-border-spread-surface-disabled) var(--sjs2-color-utility-shadow-surface-disabled)",
    "--sjs2-border-effect-surface-dragging": "var(--sjs2-border-offset-x-surface-dragging) var(--sjs2-border-offset-y-surface-dragging) var(--sjs2-border-blur-surface-dragging) var(--sjs2-border-spread-surface-dragging) var(--sjs2-color-utility-shadow-surface-dragging)",
    "--sjs2-border-effect-floating-default": "var(--sjs2-border-offset-x-floating-default) var(--sjs2-border-offset-y-floating-default) var(--sjs2-border-blur-floating-default) var(--sjs2-border-spread-floating-default) var(--sjs2-color-utility-shadow-floating-default)"
  }
};
