// Auto-generated theme: monochrome
export default {
  "themeName": "monochrome",
  "colorPalette": "light",
  "isPanelless": true,
  "cssVariables": {
    "--sjs2-color-project-brand-600": "#1C1B20",
    "--sjs2-color-utility-surface-designer": "#1c1b200d",
    "--sjs2-color-utility-shadow-surface-hovered": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-surface-pressed": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-surface-focused": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-surface-dragging": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-utility-shadow-floating-default": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x020))",
    "--sjs2-color-bg-basic-secondary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x005))",
    "--sjs2-color-bg-basic-tertiary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-basic-primary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x005))",
    "--sjs2-color-bg-basic-secondary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-basic-tertiary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-basic-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-brand-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-note-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-neutral-secondary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-neutral-tertiary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x000))",
    "--sjs2-color-bg-neutral-secondary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-neutral-tertiary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x005))",
    "--sjs2-color-bg-neutral-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-positive-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-warning-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-bg-alert-primary-disabled": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-fg-basic-primary-disabled": "rgba(from var(--sjs2-color-fg-basic-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-basic-secondary-disabled": "rgba(from var(--sjs2-color-fg-basic-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-basic-tertiary-disabled": "rgba(from var(--sjs2-color-fg-basic-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-neutral-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-fg-neutral-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-brand-primary": "var(--sjs2-color-project-brand-600)",
    "--sjs2-color-fg-brand-primary-dim": "var(--sjs2-color-project-brand-700)",
    "--sjs2-color-fg-brand-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-note-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-positive-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-warning-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-alert-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-border-basic-secondary": "var(--sjs2-palette-gray-500)",
    "--sjs2-color-component-action-alert-tertiary-muted-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-alert-tertiary-muted-surface-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-brand-tertiary-muted-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-brand-tertiary-muted-surface-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-quaternary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-surface-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-surface-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-quaternary-surface-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-formbox-default-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-formbox-readonly-border": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-formbox-hovered-bg": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-input-default-label": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-false-default-value": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-false-disabled-bg": "rgba(from var(--sjs2-color-bg-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-false-disabled-value": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-buttongroup-item-false-readonly-bg": "rgba(from var(--sjs2-color-bg-basic-secondary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-false-readonly-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-buttongroup-item-true-disabled-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-buttongroup-item-true-disabled-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-buttongroup-item-true-disabled-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-check-false-default-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-check-false-default-border": "var(--sjs2-color-border-basic-primary)",
    "--sjs2-color-component-check-true-default-bg": "var(--sjs2-color-bg-basic-primary)",
    "--sjs2-color-component-check-true-default-border": "var(--sjs2-color-border-basic-primary)",
    "--sjs2-color-component-check-true-default-icon": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-component-check-true-disabled-border": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-component-check-true-disabled-icon": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-check-true-hovered-icon": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-false-disabled-thumb": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-toggle-true-default-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-true-disabled-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-true-readonly-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-toggle-true-hovered-border": "var(--sjs2-color-border-brand-primary)",
    "--sjs2-color-component-toggle-true-hovered-thumb": "var(--sjs2-color-fg-static-1-primary)",
    "--sjs2-color-component-slider-default-fg": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-slider-default-dot": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-slider-hovered-fg": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-slider-hovered-dot": "var(--sjs2-color-fg-brand-primary)",
    "--sjs2-color-component-slider-design-fg": "var(--sjs2-color-fg-basic-tertiary)",
    "--sjs2-color-component-boolean-item-false-disabled-value": "var(--sjs2-palette-gray-250)",
    "--sjs2-color-component-boolean-item-false-readonly-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-boolean-item-true-disabled-value": "var(--sjs2-palette-gray-400)",
    "--sjs2-color-component-boolean-disabled-border": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-boolean-readonly-border": "var(--sjs2-palette-gray-250)",
    "--sjs2-opacity-hovered": "var(--sjs2-opacity-x100)",
    "--sjs2-opacity-pressed": "var(--sjs2-opacity-x100)",
    "--sjs2-border-effect-component-formbox-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-formbox-default-border)",
    "--sjs2-border-effect-component-formbox-hovered": "inset var(--sjs2-border-offset-x-form-hovered) var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-formbox-hovered-border)",
    "--sjs2-border-effect-component-formbox-focused": "inset var(--sjs2-border-offset-x-form-focused) var(--sjs2-border-offset-y-form-focused) var(--sjs2-border-blur-form-focused) var(--sjs2-border-width-x200) var(--sjs2-color-component-formbox-focused-border)",
    "--sjs2-border-effect-component-formbox-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-formbox-disabled-border)",
    "--sjs2-border-effect-component-formbox-invalid": "inset var(--sjs2-border-offset-x-form-invalid) var(--sjs2-border-offset-y-form-invalid) var(--sjs2-border-blur-form-invalid) var(--sjs2-border-width-x100) var(--sjs2-color-component-formbox-invalid-border)",
    "--sjs2-border-effect-component-formbox-invalid-focused": "inset var(--sjs2-border-offset-x-form-invalid-focused) var(--sjs2-border-offset-y-form-invalid-focused) var(--sjs2-border-blur-form-invalid-focused) var(--sjs2-border-width-x200) var(--sjs2-color-component-formbox-invalid-focused-border)",
    "--sjs2-border-effect-component-formbox-highlighted": "inset var(--sjs2-border-offset-x-form-highlighted) var(--sjs2-border-offset-y-form-highlighted) var(--sjs2-border-blur-form-highlighted) var(--sjs2-border-width-x200) var(--sjs2-color-component-formbox-highlighted-border)",
    "--sjs2-border-effect-component-formbox-readonly": "inset var(--sjs2-border-offset-x-form-readonly) var(--sjs2-border-offset-y-form-readonly) var(--sjs2-border-blur-form-readonly) var(--sjs2-border-width-x100) var(--sjs2-color-component-formbox-readonly-border)",
    "--sjs2-border-effect-component-formbox-design": "inset var(--sjs2-border-offset-x-form-design) var(--sjs2-border-offset-y-form-design) var(--sjs2-border-blur-form-design) var(--sjs2-border-width-x100) var(--sjs2-color-component-formbox-design-border)",
    "--sjs2-border-effect-component-check-false-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-check-false-default-border)",
    "--sjs2-border-effect-component-check-false-hovered": "inset var(--sjs2-border-offset-x-form-hovered) var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-check-false-hovered-border)",
    "--sjs2-border-effect-component-check-false-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-check-false-disabled-border)",
    "--sjs2-border-effect-component-check-false-design": "inset var(--sjs2-border-offset-x-form-design) var(--sjs2-border-offset-y-form-design) var(--sjs2-border-blur-form-design) var(--sjs2-border-width-x100) var(--sjs2-color-component-check-false-design-border)",
    "--sjs2-border-effect-component-check-false-readonly": "inset var(--sjs2-border-offset-x-form-readonly) var(--sjs2-border-offset-y-form-readonly) var(--sjs2-border-blur-form-readonly) var(--sjs2-border-width-x100) var(--sjs2-color-component-check-false-readonly-border)",
    "--sjs2-border-effect-component-check-false-invalid": "inset var(--sjs2-border-offset-x-form-invalid) var(--sjs2-border-offset-y-form-invalid) var(--sjs2-border-blur-form-invalid) var(--sjs2-border-width-x100) var(--sjs2-color-component-check-false-invalid-border)",
    "--sjs2-border-effect-component-check-true-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-check-true-default-border)",
    "--sjs2-border-effect-component-check-true-hovered": "inset var(--sjs2-border-offset-x-form-hovered) var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-check-true-hovered-border)",
    "--sjs2-border-effect-component-check-true-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-check-true-disabled-border)",
    "--sjs2-border-effect-component-toggle-false-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-toggle-false-default-border)",
    "--sjs2-border-effect-component-toggle-false-hovered": "inset var(--sjs2-border-offset-x-form-hovered) var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-toggle-false-hovered-border)",
    "--sjs2-border-effect-component-toggle-false-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-toggle-false-disabled-border)",
    "--sjs2-border-effect-component-toggle-true-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-toggle-true-default-border)",
    "--sjs2-border-effect-component-toggle-true-hovered": "inset var(--sjs2-border-offset-x-form-hovered) var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-toggle-true-hovered-border)",
    "--sjs2-border-effect-component-toggle-true-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-toggle-true-disabled-border)",
    "--sjs2-border-effect-component-tagbox-item-default": "inset var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-default-border)",
    "--sjs2-border-effect-component-tagbox-item-hovered": "inset var(--sjs2-border-offset-x-trigger-hovered) var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-hovered-border)",
    "--sjs2-border-effect-component-tagbox-item-disabled": "inset var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-disabled-border)",
    "--sjs2-border-effect-component-tagbox-item-readonly": "inset var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-readonly-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-default": "inset var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-default-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-hovered": "inset var(--sjs2-border-offset-x-trigger-hovered) var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-hovered-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-disabled": "inset var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-disabled-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-readonly": "inset var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-readonly-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-default": "inset var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-true-default-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-disabled": "inset var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-true-disabled-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-readonly": "inset var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-true-readonly-border)",
    "--sjs2-border-effect-component-boolean-item-false-default": "inset var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-item-false-default-border)",
    "--sjs2-border-effect-component-boolean-item-false-hovered": "inset var(--sjs2-border-offset-x-trigger-hovered) var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-item-false-hovered-border)",
    "--sjs2-border-effect-component-boolean-item-false-disabled": "inset var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-item-false-disabled-border)",
    "--sjs2-border-effect-component-boolean-item-false-readonly": "inset var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-item-false-readonly-border)",
    "--sjs2-border-effect-component-boolean-item-true-default": "inset var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-item-true-default-border)",
    "--sjs2-border-effect-component-boolean-item-true-disabled": "inset var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-item-true-disabled-border)",
    "--sjs2-border-effect-component-boolean-item-true-readonly": "inset var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-item-true-readonly-border)",
    "--sjs2-border-effect-component-boolean-default": "inset var(--sjs2-border-offset-x-form-default) var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-default-border)",
    "--sjs2-border-effect-component-boolean-disabled": "inset var(--sjs2-border-offset-x-form-disabled) var(--sjs2-border-offset-y-form-disabled) var(--sjs2-border-blur-form-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-disabled-border)",
    "--sjs2-border-effect-component-boolean-invalid": "inset var(--sjs2-border-offset-x-form-invalid) var(--sjs2-border-offset-y-form-invalid) var(--sjs2-border-blur-form-invalid) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-invalid-border)",
    "--sjs2-border-effect-component-boolean-highlighted": "inset var(--sjs2-border-offset-x-form-highlighted) var(--sjs2-border-offset-y-form-highlighted) var(--sjs2-border-blur-form-highlighted) var(--sjs2-border-width-x200) var(--sjs2-color-component-boolean-highlighted-border)",
    "--sjs2-border-effect-component-boolean-readonly": "inset var(--sjs2-border-offset-x-form-readonly) var(--sjs2-border-offset-y-form-readonly) var(--sjs2-border-blur-form-readonly) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-readonly-border)",
    "--sjs2-border-effect-component-boolean-design": "inset var(--sjs2-border-offset-x-form-design) var(--sjs2-border-offset-y-form-design) var(--sjs2-border-blur-form-design) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-design-border)",
    "--sjs2-border-effect-trigger-default": "var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-default)",
    "--sjs2-border-effect-trigger-hovered": "var(--sjs2-border-offset-x-trigger-hovered) var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-hovered)",
    "--sjs2-border-effect-trigger-pressed": "var(--sjs2-border-offset-x-trigger-pressed) var(--sjs2-border-offset-y-trigger-pressed) var(--sjs2-border-blur-trigger-pressed) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-pressed)",
    "--sjs2-border-effect-trigger-disabled": "var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-disabled)",
    "--sjs2-border-effect-trigger-design": "var(--sjs2-border-offset-x-trigger-design) var(--sjs2-border-offset-y-trigger-design) var(--sjs2-border-blur-trigger-design) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-design)",
    "--sjs2-border-effect-trigger-readonly": "var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-readonly)",
    "--sjs2-border-effect-trigger-invalid": "var(--sjs2-border-offset-x-trigger-invalid) var(--sjs2-border-offset-y-trigger-invalid) var(--sjs2-border-blur-trigger-invalid) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-invalid)",
    "--sjs2-border-effect-surface-default": "var(--sjs2-border-offset-x-surface-default) var(--sjs2-border-offset-y-surface-default) var(--sjs2-border-blur-surface-default) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-surface-default)",
    "--sjs2-border-effect-surface-hovered": "var(--sjs2-border-offset-x-surface-hovered) var(--sjs2-border-offset-y-surface-hovered) var(--sjs2-border-blur-surface-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-surface-hovered)",
    "--sjs2-border-effect-surface-pressed": "var(--sjs2-border-offset-x-surface-pressed) var(--sjs2-border-offset-y-surface-pressed) var(--sjs2-border-blur-surface-pressed) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-surface-pressed)",
    "--sjs2-border-effect-surface-focused": "var(--sjs2-border-offset-x-surface-focused) var(--sjs2-border-offset-y-surface-focused) var(--sjs2-border-blur-surface-focused) var(--sjs2-border-width-x200) var(--sjs2-color-utility-shadow-surface-focused)",
    "--sjs2-border-effect-surface-disabled": "var(--sjs2-border-offset-x-surface-disabled) var(--sjs2-border-offset-y-surface-disabled) var(--sjs2-border-blur-surface-disabled) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-surface-disabled)",
    "--sjs2-border-effect-surface-dragging": "var(--sjs2-border-offset-x-surface-dragging) var(--sjs2-border-offset-y-surface-dragging) var(--sjs2-border-blur-surface-dragging) var(--sjs2-border-spread-surface-dragging) var(--sjs2-color-utility-shadow-surface-dragging)",
    "--sjs2-border-effect-floating-default": "var(--sjs2-border-offset-x-floating-default) var(--sjs2-border-offset-y-floating-default) var(--sjs2-border-blur-floating-default) var(--sjs2-border-spread-floating-default) var(--sjs2-color-utility-shadow-floating-default)",
    "--sjs2-color-project-brand-400": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 1.2))",
    "--sjs2-color-project-brand-700": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 0.85))",
    "--sjs2-color-project-brand-800": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 0.75))",
    "--sjs2-color-bg-static-2-primary-dim": "hsl(from var(--sjs2-palette-gray-100) h s calc(l * 1.1))"
  }
};
