// Auto-generated theme: plain
export default {
  "themeName": "plain",
  "colorPalette": "light",
  "isPanelless": true,
  "cssVariables": {
    "--sjs2-layout-component-page-content-area-gap-horizontal": "var(--sjs2-spacing-large-horizontal)",
    "--sjs2-layout-component-page-content-area-gap-vertical": "var(--sjs2-spacing-large-vertical)",
    "--sjs2-layout-component-panel-simple-box-gap-vertical": "var(--sjs2-spacing-medium-vertical)",
    "--sjs2-layout-component-panel-simple-content-area-padding-horizontal": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-component-panel-simple-content-area-padding-top": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-component-panel-simple-content-area-padding-bottom": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-component-panel-simple-content-area-gap-horizontal": "var(--sjs2-spacing-x500)",
    "--sjs2-radius-component-panel-simple": "var(--sjs2-radius-x000)",
    "--sjs2-is-panelless": "true",
    "--sjs2-color-project-brand-600": "rgba(37, 137, 229, 1)",
    "--sjs2-color-utility-surface-survey": "var(--sjs2-color-component-panel-default-bg)",
    "--sjs2-color-utility-surface-designer": "rgba(255, 255, 255, 1)",
    "--sjs2-color-bg-basic-secondary": "rgba(255, 255, 255, 1)",
    "--sjs2-color-bg-basic-primary-dim": "rgba(248, 248, 248, 1)",
    "--sjs2-color-bg-basic-secondary-dim": "rgba(243, 243, 243, 1)",
    "--sjs2-color-bg-neutral-tertiary-dim": "rgba(255, 255, 255, 1)",
    "--sjs2-color-bg-brand-secondary": "rgba(37, 137, 229, 0.1)",
    "--sjs2-color-bg-brand-primary-dim": "rgba(21, 119, 209, 1)",
    "--sjs2-color-bg-note-secondary": "rgba(67, 127, 217, 0.1)",
    "--sjs2-color-bg-positive-secondary": "rgba(25, 179, 148, 0.1)",
    "--sjs2-color-bg-warning-secondary": "rgba(255, 152, 20, 0.1)",
    "--sjs2-color-bg-alert-secondary": "rgba(229, 10, 62, 0.1)",
    "--sjs2-color-fg-basic-primary": "rgba(0, 0, 0, 0.91)",
    "--sjs2-color-fg-basic-secondary": "rgba(0, 0, 0, 0.45)",
    "--sjs2-color-fg-brand-primary-disabled": "rgba(255, 255, 255, 0.25)",
    "--sjs2-color-border-basic-secondary": "rgba(0, 0, 0, 0.15)",
    "--sjs2-color-border-basic-secondary-overlay": "rgba(0, 0, 0, 0.16)",
    "--sjs2-color-data-chart-track-color-0": "var(--sjs2-palette-gray-150)",
    "--sjs2-color-component-panel-nested-default-border": "var(--sjs2-color-utility-shadow-surface-default)",
    "--sjs2-color-component-panel-simple-default-bg": "transparent",
    "--sjs2-color-component-panel-simple-default-border": "transparent",
    "--sjs2-border-effect-component-formbox-default": "0px 0px 0px 1px rgba(0, 0, 0, 0.15)",
    "--sjs2-border-effect-surface-default": "0px 0px 0px 1px rgba(0, 0, 0, 0.15)",
    "--sjs2-border-effect-floating-default": "0px 0px 0px 1px rgba(0, 0, 0, 0.1), 0px 8px 16px 0px rgba(0, 0, 0, 0.05)"
  }
};
