// Auto-generated theme: soft
export default {
  "themeName": "soft",
  "isPanelless": true,
  "cssVariables": {
    "--sjs2-color-utility-shadow-trigger-default": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-trigger-hovered": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-trigger-pressed": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-trigger-disabled": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x005))",
    "--sjs2-color-utility-shadow-trigger-design": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-component-formbox-disabled-bg": "var(--sjs2-color-bg-basic-primary-disabled)",
    "--sjs2-color-component-formbox-invalid-bg": "var(--sjs2-color-bg-alert-secondary)",
    "--sjs2-color-component-formbox-invalid-focused-bg": "var(--sjs2-color-bg-alert-secondary)",
    "--sjs2-color-component-input-disabled-line": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-check-false-invalid-bg": "var(--sjs2-color-bg-alert-secondary)",
    "--sjs2-opacity-hovered": "var(--sjs2-opacity-x100)",
    "--sjs2-opacity-pressed": "var(--sjs2-opacity-x100)",
    "--sjs2-border-effect-component-formbox-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-formbox-default-border)",
    "--sjs2-border-effect-component-formbox-hovered": "inset 0px 1px 2px 0px var(--sjs2-color-component-formbox-hovered-border)",
    "--sjs2-border-effect-component-formbox-design": "inset 0px 1px 2px 0px var(--sjs2-color-component-formbox-design-border)",
    "--sjs2-border-effect-component-check-false-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-check-false-default-border)",
    "--sjs2-border-effect-component-check-false-hovered": "inset 0px 1px 2px 0px var(--sjs2-color-component-check-false-hovered-border)",
    "--sjs2-border-effect-component-check-false-design": "inset 0px 1px 2px 0px var(--sjs2-color-component-check-false-design-border)",
    "--sjs2-border-effect-component-check-true-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-check-true-default-border)",
    "--sjs2-border-effect-component-check-true-hovered": "inset 0px 1px 2px 0px var(--sjs2-color-component-check-true-hovered-border)",
    "--sjs2-border-effect-component-toggle-false-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-toggle-false-default-border)",
    "--sjs2-border-effect-component-toggle-false-hovered": "inset 0px 1px 2px 0px var(--sjs2-color-component-toggle-false-hovered-border)",
    "--sjs2-border-effect-component-toggle-true-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-toggle-true-default-border)",
    "--sjs2-border-effect-component-toggle-true-hovered": "inset 0px 1px 2px 0px var(--sjs2-color-component-toggle-true-hovered-border)",
    "--sjs2-border-effect-component-tagbox-item-default": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-default-border)",
    "--sjs2-border-effect-component-tagbox-item-hovered": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-hovered-border)",
    "--sjs2-border-effect-component-tagbox-item-disabled": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-disabled-border)",
    "--sjs2-border-effect-component-tagbox-item-readonly": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-readonly-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-default": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-default-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-hovered": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-hovered-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-disabled": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-disabled-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-readonly": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-readonly-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-default": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-true-default-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-disabled": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-true-disabled-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-readonly": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-true-readonly-border)",
    "--sjs2-border-effect-trigger-default": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-default)",
    "--sjs2-border-effect-trigger-hovered": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-hovered)",
    "--sjs2-border-effect-trigger-design": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-design)",
    "--sjs2-border-effect-surface-default": "0px 2px 4px var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-surface-default)"
  }
};
