// Auto-generated theme: soft
export default {
  "themeName": "soft",
  "colorPalette": "dark",
  "cssVariables": {
    "--sjs2-color-project-brand-400": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 1.2))",
    "--sjs2-color-project-brand-700": "lch(from var(--sjs2-color-project-brand-600) calc(l * 0.85) c h)",
    "--sjs2-color-utility-body": "var(--sjs2-palette-gray-999)",
    "--sjs2-color-utility-sheet": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-utility-a11y": "rgba(from var(--sjs2-palette-blue-400) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-utility-scrollbar": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-utility-toolbox": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-utility-property-grid": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-utility-tabs": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-utility-surface-survey": "#161519",
    "--sjs2-color-utility-surface-survey-panelless": "#1c1b200d",
    "--sjs2-color-utility-surface-designer": "#161519",
    "--sjs2-color-utility-surface-json-editor": "var(--sjs2-color-utility-surface-designer)",
    "--sjs2-color-utility-shadow-surface-default": "var(--sjs2-color-border-basic-secondary)",
    "--sjs2-color-utility-shadow-surface-dragging": "rgba(from #004C44 r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-floating-default": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x060))",
    "--sjs2-color-bg-basic-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-bg-basic-secondary": "var(--sjs2-palette-gray-850)",
    "--sjs2-color-bg-basic-tertiary": "var(--sjs2-palette-gray-800)",
    "--sjs2-color-bg-basic-primary-dim": "var(--sjs2-palette-gray-850)",
    "--sjs2-color-bg-basic-secondary-dim": "var(--sjs2-palette-gray-800)",
    "--sjs2-color-bg-basic-tertiary-dim": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-basic-primary-disabled": "var(--sjs2-palette-gray-850)",
    "--sjs2-color-bg-neutral-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-bg-neutral-secondary": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-bg-neutral-tertiary": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x000))",
    "--sjs2-color-bg-neutral-primary-dim": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-bg-neutral-secondary-dim": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x020))",
    "--sjs2-color-bg-neutral-tertiary-dim": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-neutral-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-brand-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-note-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-positive-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-warning-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-bg-alert-primary-disabled": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-fg-basic-primary": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x085))",
    "--sjs2-color-fg-basic-primary-muted": "var(--sjs2-color-fg-basic-primary)",
    "--sjs2-color-fg-basic-primary-disabled": "rgba(from var(--sjs2-color-fg-basic-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-basic-secondary-disabled": "rgba(from var(--sjs2-color-fg-basic-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-basic-tertiary-disabled": "rgba(from var(--sjs2-color-fg-basic-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-neutral-on-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-fg-neutral-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-brand-primary": "var(--sjs2-color-project-brand-400)",
    "--sjs2-color-fg-brand-primary-dim": "var(--sjs2-color-project-brand-700)",
    "--sjs2-color-fg-brand-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-note-primary": "var(--sjs2-palette-blue-400)",
    "--sjs2-color-fg-note-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-positive-primary": "var(--sjs2-palette-green-400)",
    "--sjs2-color-fg-positive-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-warning-primary": "var(--sjs2-palette-yellow-400)",
    "--sjs2-color-fg-warning-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-fg-alert-primary": "var(--sjs2-palette-red-400)",
    "--sjs2-color-fg-alert-primary-disabled": "rgba(from var(--sjs2-color-fg-neutral-primary) r g b / var(--sjs2-opacity-x025))",
    "--sjs2-color-border-basic-primary": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-border-basic-secondary": "var(--sjs2-palette-gray-750)",
    "--sjs2-color-border-basic-secondary-overlay": "rgba(from var(--sjs2-color-border-basic-primary) r g b / var(--sjs2-opacity-x020))",
    "--sjs2-color-border-basic-secondary-disabled": "var(--sjs2-palette-gray-800)",
    "--sjs2-color-border-neutral-primary": "var(--sjs2-palette-gray-900)",
    "--sjs2-color-component-action-alert-tertiary-muted-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-alert-tertiary-muted-surface-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-brand-tertiary-muted-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-brand-tertiary-muted-surface-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-secondary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-quaternary-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-surface-default-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-tertiary-surface-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-action-neutral-quaternary-surface-hovered-label": "var(--sjs2-color-fg-neutral-primary)",
    "--sjs2-color-component-input-disabled-line": "var(--sjs2-palette-gray-800)",
    "--sjs2-color-component-buttongroup-item-false-default-bg": "rgba(from var(--sjs2-color-bg-basic-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-false-disabled-bg": "rgba(from var(--sjs2-color-bg-basic-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-buttongroup-item-false-readonly-bg": "rgba(from var(--sjs2-color-bg-basic-primary) r g b / var(--sjs2-opacity-hidden))",
    "--sjs2-color-component-slider-default-thumb": "var(--sjs2-color-bg-neutral-primary)",
    "--sjs2-color-component-slider-disabled-thumb": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-slider-readonly-thumb": "var(--sjs2-color-bg-basic-secondary)",
    "--sjs2-color-component-slider-hovered-thumb": "var(--sjs2-color-bg-neutral-primary)",
    "--sjs2-color-component-slider-invalid-thumb": "var(--sjs2-color-bg-neutral-primary)",
    "--sjs2-color-component-slider-design-thumb": "var(--sjs2-color-bg-neutral-primary)",
    "--sjs2-color-component-slider-design-dot": "var(--sjs2-color-bg-neutral-primary)",
    "--sjs2-opacity-hovered": "var(--sjs2-opacity-x100)",
    "--sjs2-opacity-pressed": "var(--sjs2-opacity-x100)",
    "--sjs2-border-effect-component-formbox-default": "inset 0px var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-formbox-default-border)",
    "--sjs2-border-effect-component-formbox-hovered": "inset 0px var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-spread-form-hovered) var(--sjs2-color-component-formbox-hovered-border)",
    "--sjs2-border-effect-component-formbox-design": "inset 0px var(--sjs2-border-offset-y-form-design) var(--sjs2-border-blur-form-design) var(--sjs2-border-spread-form-design) var(--sjs2-color-component-formbox-design-border)",
    "--sjs2-border-effect-component-check-false-default": "inset 0px var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-check-false-default-border)",
    "--sjs2-border-effect-component-check-false-hovered": "inset 0px var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-spread-form-hovered) var(--sjs2-color-component-check-false-hovered-border)",
    "--sjs2-border-effect-component-check-false-design": "inset 0px var(--sjs2-border-offset-y-form-design) var(--sjs2-border-blur-form-design) var(--sjs2-border-spread-form-design) var(--sjs2-color-component-check-false-design-border)",
    "--sjs2-border-effect-component-check-true-default": "inset 0px var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-check-true-default-border)",
    "--sjs2-border-effect-component-check-true-hovered": "inset 0px var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-spread-form-hovered) var(--sjs2-color-component-check-true-hovered-border)",
    "--sjs2-border-effect-component-toggle-false-default": "inset 0px var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-toggle-false-default-border)",
    "--sjs2-border-effect-component-toggle-false-hovered": "inset 0px var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-spread-form-hovered) var(--sjs2-color-component-toggle-false-hovered-border)",
    "--sjs2-border-effect-component-toggle-true-default": "inset 0px var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-toggle-true-default-border)",
    "--sjs2-border-effect-component-toggle-true-hovered": "inset 0px var(--sjs2-border-offset-y-form-hovered) var(--sjs2-border-blur-form-hovered) var(--sjs2-border-spread-form-hovered) var(--sjs2-color-component-toggle-true-hovered-border)",
    "--sjs2-border-effect-component-tagbox-item-default": "inset 0px var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-default-border)",
    "--sjs2-border-effect-component-tagbox-item-hovered": "inset 0px var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-hovered-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-default": "inset 0px var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-default-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-hovered": "inset 0px var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-hovered-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-default": "inset 0px var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-true-default-border)",
    "--sjs2-border-effect-component-boolean-item-false-default": "inset 0px var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-item-false-default-border)",
    "--sjs2-border-effect-component-boolean-item-false-hovered": "inset 0px var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-item-false-hovered-border)",
    "--sjs2-border-effect-component-boolean-item-true-default": "inset 0px var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-component-boolean-item-true-default-border)",
    "--sjs2-border-effect-component-boolean-default": "inset 0px var(--sjs2-border-offset-y-form-default) var(--sjs2-border-blur-form-default) var(--sjs2-border-spread-form-default) var(--sjs2-color-component-boolean-default-border)",
    "--sjs2-border-effect-component-boolean-design": "inset 0px var(--sjs2-border-offset-y-form-design) var(--sjs2-border-blur-form-design) var(--sjs2-border-spread-form-design) var(--sjs2-color-component-boolean-design-border)",
    "--sjs2-border-effect-trigger-default": "0px var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-default)",
    "--sjs2-border-effect-trigger-hovered": "0px var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-hovered)",
    "--sjs2-border-effect-trigger-design": "0px var(--sjs2-border-offset-y-trigger-design) var(--sjs2-border-blur-trigger-design) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-design)",
    "--sjs2-border-effect-surface-default": "0px var(--sjs2-border-offset-y-surface-default) var(--sjs2-border-blur-surface-default) var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-surface-default)",
    "--sjs2-border-effect-surface-pressed": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-surface-pressed)",
    "--sjs2-border-effect-surface-dragging": "0px var(--sjs2-border-offset-y-surface-dragging) var(--sjs2-border-blur-surface-dragging) var(--sjs2-border-width-x400) var(--sjs2-color-utility-shadow-surface-dragging)",
    "--sjs2-border-effect-floating-default": "0px 6px 12px 0px var(--sjs2-color-utility-shadow-floating-default)"
  }
};
