// Auto-generated theme: soft
export default {
  "themeName": "soft",
  "colorPalette": "light",
  "cssVariables": {
    "--sjs2-color-utility-shadow-trigger-default": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-trigger-hovered": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-trigger-pressed": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-trigger-disabled": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x005))",
    "--sjs2-color-utility-shadow-trigger-design": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-component-formbox-disabled-bg": "var(--sjs2-color-bg-basic-primary-disabled)",
    "--sjs2-color-component-formbox-invalid-bg": "var(--sjs2-color-bg-alert-secondary)",
    "--sjs2-color-component-formbox-invalid-focused-bg": "var(--sjs2-color-bg-alert-secondary)",
    "--sjs2-color-component-check-false-invalid-bg": "var(--sjs2-color-bg-alert-secondary)",
    "--sjs2-opacity-hovered": "var(--sjs2-opacity-x100)",
    "--sjs2-opacity-pressed": "var(--sjs2-opacity-x100)",
    "--sjs2-border-spread-surface-dragging": "var(--sjs2-border-width-x400)",
    "--sjs2-border-effect-component-formbox-focused": "var(--sjs2-border-offset-x-form-focused) var(--sjs2-border-offset-y-form-focused) var(--sjs2-border-blur-form-focused) var(--sjs2-border-spread-form-focused) var(--sjs2-color-component-formbox-focused-border)",
    "--sjs2-border-effect-component-formbox-invalid-focused": "var(--sjs2-border-offset-x-form-invalid-focused) var(--sjs2-border-offset-y-form-invalid-focused) var(--sjs2-border-blur-form-invalid-focused) var(--sjs2-border-spread-form-invalid-focused) var(--sjs2-color-component-formbox-invalid-focused-border)",
    "--sjs2-border-effect-component-formbox-highlighted": "var(--sjs2-border-offset-x-form-highlighted) var(--sjs2-border-offset-y-form-highlighted) var(--sjs2-border-blur-form-highlighted) var(--sjs2-border-spread-form-highlighted) var(--sjs2-color-component-formbox-highlighted-border)",
    "--sjs2-border-effect-component-tagbox-item-default": "var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-spread-trigger-default) var(--sjs2-color-component-tagbox-item-default-border)",
    "--sjs2-border-effect-component-tagbox-item-hovered": "var(--sjs2-border-offset-x-trigger-hovered) var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-spread-trigger-hovered) var(--sjs2-color-component-tagbox-item-hovered-border)",
    "--sjs2-border-effect-component-tagbox-item-disabled": "var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-spread-trigger-disabled) var(--sjs2-color-component-tagbox-item-disabled-border)",
    "--sjs2-border-effect-component-tagbox-item-readonly": "var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-spread-trigger-readonly) var(--sjs2-color-component-tagbox-item-readonly-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-default": "var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-spread-trigger-default) var(--sjs2-color-component-buttongroup-item-false-default-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-hovered": "var(--sjs2-border-offset-x-trigger-hovered) var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-spread-trigger-hovered) var(--sjs2-color-component-buttongroup-item-false-hovered-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-disabled": "var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-spread-trigger-disabled) var(--sjs2-color-component-buttongroup-item-false-disabled-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-readonly": "var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-spread-trigger-readonly) var(--sjs2-color-component-buttongroup-item-false-readonly-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-default": "var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-spread-trigger-default) var(--sjs2-color-component-buttongroup-item-true-default-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-disabled": "var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-spread-trigger-disabled) var(--sjs2-color-component-buttongroup-item-true-disabled-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-readonly": "var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-spread-trigger-readonly) var(--sjs2-color-component-buttongroup-item-true-readonly-border)",
    "--sjs2-border-effect-component-boolean-item-false-default": "var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-spread-trigger-default) var(--sjs2-color-component-boolean-item-false-default-border)",
    "--sjs2-border-effect-component-boolean-item-false-hovered": "var(--sjs2-border-offset-x-trigger-hovered) var(--sjs2-border-offset-y-trigger-hovered) var(--sjs2-border-blur-trigger-hovered) var(--sjs2-border-spread-trigger-hovered) var(--sjs2-color-component-boolean-item-false-hovered-border)",
    "--sjs2-border-effect-component-boolean-item-false-disabled": "var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-spread-trigger-disabled) var(--sjs2-color-component-boolean-item-false-disabled-border)",
    "--sjs2-border-effect-component-boolean-item-false-readonly": "var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-spread-trigger-readonly) var(--sjs2-color-component-boolean-item-false-readonly-border)",
    "--sjs2-border-effect-component-boolean-item-true-default": "var(--sjs2-border-offset-x-trigger-default) var(--sjs2-border-offset-y-trigger-default) var(--sjs2-border-blur-trigger-default) var(--sjs2-border-spread-trigger-default) var(--sjs2-color-component-boolean-item-true-default-border)",
    "--sjs2-border-effect-component-boolean-item-true-disabled": "var(--sjs2-border-offset-x-trigger-disabled) var(--sjs2-border-offset-y-trigger-disabled) var(--sjs2-border-blur-trigger-disabled) var(--sjs2-border-spread-trigger-disabled) var(--sjs2-color-component-boolean-item-true-disabled-border)",
    "--sjs2-border-effect-component-boolean-item-true-readonly": "var(--sjs2-border-offset-x-trigger-readonly) var(--sjs2-border-offset-y-trigger-readonly) var(--sjs2-border-blur-trigger-readonly) var(--sjs2-border-spread-trigger-readonly) var(--sjs2-color-component-boolean-item-true-readonly-border)"
  }
};
