// Auto-generated theme: test
export default {
  "themeName": "test",
  "iconSet": "v2",
  "cssVariables": {
    "--sjs2-base-unit-spacing": "var(--sjs2-base-unit-size)",
    "--sjs2-base-unit-radius": "4px",
    "--sjs2-base-unit-line-height": "var(--sjs2-base-unit-font-size)",
    "--sjs2-radius-component-drop": "4px",
    "--sjs2-radius-component-page": "8px",
    "--sjs2-radius-component-panel": "4px",
    "--sjs2-radius-component-modal": "8px",
    "--sjs2-typography-font-size-component-header-description": "20px",
    "--sjs2-typography-line-height-component-page-title": "calc(1.33 * var(--sjs2-typography-font-size-component-page-title))",
    "--sjs2-typography-line-height-component-header-description": "calc(1.5 * var(--sjs2-typography-font-size-component-header-description))",
    "--sjs2-typography-font-weight-component-page-title": "700",
    "--sjs2-typography-font-weight-component-header-title": "700",
    "--sjs2-color-project-brand-400": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 1.2))",
    "--sjs2-color-utility-surface-survey": "#f3f3f3",
    "--sjs2-color-utility-shadow-trigger-default": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-trigger-hovered": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-trigger-pressed": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-trigger-disabled": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x005))",
    "--sjs2-color-utility-shadow-trigger-design": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-bg-neutral-tertiary-dim": "#f3f3f3",
    "--sjs2-color-component-action-neutral-tertiary-default-icon": "rgba(from #1c1b20 r g b / calc(1% * 60))",
    "--sjs2-color-component-action-neutral-tertiary-hovered-bg": "#f3f3f3",
    "--sjs2-color-component-action-neutral-tertiary-hovered-icon": "#909090",
    "--sjs2-color-component-formbox-disabled-bg": "var(--sjs2-color-bg-basic-primary-disabled)",
    "--sjs2-color-component-formbox-readonly-bg": "#f8f8f8",
    "--sjs2-color-component-formbox-invalid-bg": "rgba(230, 10, 62, .1)",
    "--sjs2-color-component-formbox-invalid-focused-bg": "rgba(230, 10, 62, .1)",
    "--sjs2-color-component-input-disabled-line": "var(--sjs2-palette-gray-100)",
    "--sjs2-color-component-buttongroup-item-false-default-value": "#1c1b20",
    "--sjs2-color-component-check-false-invalid-bg": "rgba(230, 10, 62, .1)",
    "--sjs2-color-component-boolean-item-false-hovered-value": "rgba(0, 0, 0, 0.45)",
    "--sjs2-color-component-boolean-item-true-readonly-border": "#161616",
    "--sjs2-color-component-boolean-readonly-border": "transparent",
    "--sjs2-color-component-boolean-invalid-bg": "rgba(230, 10, 62, .1)",
    "--sjs2-color-component-boolean-invalid-border": "rgba(0, 0, 0, 0.15)",
    "--sjs2-color-component-tagbox-item-default-bg": "#19b394",
    "--sjs2-color-component-tagbox-item-default-border": "transparent",
    "--sjs2-color-component-tagbox-item-default-label": "#ffffff",
    "--sjs2-color-component-tagbox-item-hovered-bg": "#19b394",
    "--sjs2-color-component-tagbox-item-hovered-border": "transparent",
    "--sjs2-color-component-tagbox-item-hovered-label": "#ffffff",
    "--sjs2-color-component-tagbox-item-action-default-bg": "rgba(255, 255, 255, 0.25)",
    "--sjs2-color-component-tagbox-item-action-default-icon": "#ffffff",
    "--sjs2-color-component-tagbox-item-action-hovered-bg": "rgba(255, 255, 255, 0.25)",
    "--sjs2-color-component-tagbox-item-action-hovered-icon": "#ffffff",
    "--sjs2-opacity-hovered": "var(--sjs2-opacity-x100)",
    "--sjs2-opacity-pressed": "var(--sjs2-opacity-x100)",
    "--sjs2-border-effect-component-formbox-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-formbox-default-border)",
    "--sjs2-border-effect-component-formbox-hovered": "inset 0px 1px 2px 0px var(--sjs2-color-component-formbox-hovered-border)",
    "--sjs2-border-effect-component-formbox-focused": "0px 0px 0px 2px var(--sjs2-color-bg-brand-primary)",
    "--sjs2-border-effect-component-formbox-invalid": "inset 0 1px 2px 0 rgba(0, 0, 0, 0.15)",
    "--sjs2-border-effect-component-formbox-invalid-focused": "0px 0px 0px 2px var(--sjs2-color-bg-brand-primary)",
    "--sjs2-border-effect-component-formbox-readonly": "none",
    "--sjs2-border-effect-component-formbox-design": "inset 0px 1px 2px 0px var(--sjs2-color-component-formbox-design-border)",
    "--sjs2-border-effect-component-check-false-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-check-false-default-border)",
    "--sjs2-border-effect-component-check-false-hovered": "inset 0px 1px 2px 0px var(--sjs2-color-component-check-false-hovered-border)",
    "--sjs2-border-effect-component-check-false-design": "inset 0px 1px 2px 0px var(--sjs2-color-component-check-false-design-border)",
    "--sjs2-border-effect-component-check-false-invalid": "inset 0 1px 2px 0 rgba(0, 0, 0, 0.15)",
    "--sjs2-border-effect-component-check-true-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-check-true-default-border)",
    "--sjs2-border-effect-component-check-true-hovered": "inset 0px 1px 2px 0px var(--sjs2-color-component-check-true-hovered-border)",
    "--sjs2-border-effect-component-toggle-false-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-toggle-false-default-border)",
    "--sjs2-border-effect-component-toggle-false-hovered": "inset 0px 1px 2px 0px var(--sjs2-color-component-toggle-false-hovered-border)",
    "--sjs2-border-effect-component-toggle-true-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-toggle-true-default-border)",
    "--sjs2-border-effect-component-toggle-true-hovered": "inset 0px 1px 2px 0px var(--sjs2-color-component-toggle-true-hovered-border)",
    "--sjs2-border-effect-component-tagbox-item-default": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-default-border)",
    "--sjs2-border-effect-component-tagbox-item-hovered": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-hovered-border)",
    "--sjs2-border-effect-component-tagbox-item-disabled": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-disabled-border)",
    "--sjs2-border-effect-component-tagbox-item-readonly": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-tagbox-item-readonly-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-default": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-default-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-hovered": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-hovered-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-disabled": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-disabled-border)",
    "--sjs2-border-effect-component-buttongroup-item-false-readonly": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-false-readonly-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-default": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-true-default-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-disabled": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-true-disabled-border)",
    "--sjs2-border-effect-component-buttongroup-item-true-readonly": "0px 0px 0px var(--sjs2-border-width-x100) var(--sjs2-color-component-buttongroup-item-true-readonly-border)",
    "--sjs2-border-effect-component-boolean-item-false-default": "0px 0px 0px 0px var(--sjs2-color-component-boolean-item-false-default-border)",
    "--sjs2-border-effect-component-boolean-item-false-hovered": "0px 0px 0px 0px var(--sjs2-color-component-boolean-item-false-hovered-border)",
    "--sjs2-border-effect-component-boolean-item-false-disabled": "0px 0px 0px 0px var(--sjs2-color-component-boolean-item-false-disabled-border)",
    "--sjs2-border-effect-component-boolean-item-false-readonly": "0px 0px 0px 0px var(--sjs2-color-component-boolean-item-false-readonly-border)",
    "--sjs2-border-effect-component-boolean-item-true-default": "0px 2px 4px 0px var(--sjs2-color-component-boolean-item-true-default-border)",
    "--sjs2-border-effect-component-boolean-item-true-disabled": "inset 0px 0px 0px var(--sjs2-border-width-x200) var(--sjs2-color-component-boolean-item-true-disabled-border)",
    "--sjs2-border-effect-component-boolean-item-true-readonly": "inset 0px 0px 0px var(--sjs2-border-width-x200) var(--sjs2-color-component-boolean-item-true-readonly-border)",
    "--sjs2-border-effect-component-boolean-default": "inset 0px 1px 2px 0px var(--sjs2-color-component-boolean-default-border)",
    "--sjs2-border-effect-component-boolean-invalid": "inset 0 1px 2px 0 rgba(0, 0, 0, 0.15)",
    "--sjs2-border-effect-component-boolean-design": "inset 0px 1px 2px 0px var(--sjs2-color-component-boolean-design-border)",
    "--sjs2-border-effect-trigger-default": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-default)",
    "--sjs2-border-effect-trigger-hovered": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-hovered)",
    "--sjs2-border-effect-trigger-design": "0px 1px 2px var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-trigger-design)",
    "--sjs2-border-effect-surface-default": "0px 2px 4px var(--sjs2-border-width-x100) var(--sjs2-color-utility-shadow-surface-default)",
    "--sjs2-border-effect-surface-dragging": "0px 6px 12px var(--sjs2-border-width-x400) var(--sjs2-color-utility-shadow-surface-dragging)",
    "--sjs2-color-component-check-true-readonly-icon": "#161616",
    "--sjs2-color-component-track-default-bg": "#d4d4d4",
    "--sjs2-color-project-brand-700": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 0.85))",
    "--sjs2-color-project-brand-800": "hsl(from var(--sjs2-color-project-brand-600) h s calc(l * 0.75))",
    "--sjs2-color-bg-static-2-primary-dim": "hsl(from var(--sjs2-palette-gray-100) h s calc(l * 1.1))"
  }
};
