steps:
  - checkout: none
  - download: ReleaseVersion
    artifact: ReleaseVersionFile
  - powershell: |
      $version = Get-Content $(Pipeline.Workspace)/ReleaseVersion/ReleaseVersionFile/version.txt
      Write-Host "version: $version"
      Write-Host "##vso[task.setvariable variable=VERSION;isOutput=true]$version"
    name: data
    displayName: "version variable from version file"