parameters:
  - name: checkout
    type: string
    default: self
  - name: store
    type: boolean
    default: false

steps:
  - checkout: ${{ parameters.checkout }}
    displayName: "Checkout ${{ parameters.checkout }}"

  - script: git fetch origin pull/$(PR)/head && git checkout FETCH_HEAD
    workingDirectory: $(Build.SourcesDirectory)
    condition: ne(variables['PR'], '')
    displayName: "Switch to PR $(PR)"

  - template: ../../utils/npm.yml
    parameters:
      directories: 
        - $(Build.SourcesDirectory)
        - $(Build.SourcesDirectory)/packages/survey-core

  - ${{ if eq(parameters.store, true) }}:
    - script: npm run release -- --release-as $(VERSION) --skip.tag
      workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
      displayName: "npm run release"

    - script: echo "This runs only on merge"
      condition: eq(variables['Build.Reason'], 'PullRequest')

  - script: npm run build:all
    workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
    displayName: "Build"

  - ${{ if eq(parameters.store, true) }}:
    - script: |
        npm run doc_gen
        cp docs/surveyjs_definition.json build/surveyjs_definition.json
      workingDirectory: $(Build.SourcesDirectory)/packages/survey-core
      displayName: "Generate Docs"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-core/build"
        ArtifactName: $(ArtifactNameLibraryCore)
        StoreAsTar: true
      