export let menuListCss = {
  root: "sd-menu-list__container",
  item: "sd-menu-item",
  loadingIndicator: "sd-menu-list__loading-indicator",
  itemLabel: "sd-menu-item--label",
  itemSelected: "sd-menu-item--selected",
  itemGroup: "sd-menu-item--group",
  itemGroupSelected: "sd-menu-item--group-selected",
  itemWithIcon: "sd-menu-item--with-icon",
  itemDisabled: "sd-menu-item--disabled",
  itemFocused: "sd-menu-item--focused",
  itemHovered: "sd-menu-item--hovered",
  itemCustomValue: "sd-menu-item--custom-value",
  itemTextWrap: "sd-menu-item__text--wrap",
  itemIcon: "sd-menu-item__icon",
  itemMarkerIcon: "sd-menu-item__marker-icon",
  itemSeparator: "sd-menu-item__separator",
  itemBody: "sd-menu-item__body",
  itemsContainer: "sd-menu-list",
  itemsContainerFiltering: "sd-menu-list--filtering",
  filter: "sd-menu-filter",
  filterBox: "sd-menu-filter__box",
  filterIcon: "sd-menu-filter__icon",
  filterInput: "sd-menu-filter__input",
  searchClearButtonIcon: "sd-menu-filter__clear-button",
  emptyContainer: "sd-menu-list__empty-container",
  emptyText: "sd-menu-list__empty-text"
};