//Uncomment this line on creating a translation file
import { surveyLocalization } from "../surveyStrings";

export var urduSurveyStrings = {
  pagePrevText: "پچھلا",
  pageNextText: "اگلا",
  completeText: "مکمل",
  previewText: "دیکهنا",
  editText: "ترمیم",
  startSurveyText: "شروع کریں",
  otherItemText: "دیگر (بیان کریں)",
  noneItemText: "کوئی نہیں",
  selectAllItemText: "تمام منتخب کریں",
  progressText: "صفحہ {0} از {1}",
  panelDynamicProgressText: "ریکارڈ {0} {1}",
  questionsProgressText: " سوالات کا جواب دیا۔ {0}/{1}",
  emptySurvey: "سروے میں کوئی نظر آنے والا صفحہ یا سوال نہیں ہے۔",
  completingSurvey: "سروے مکمل کرنے کے لیے آپ کا شکریہ!",
  completingSurveyBefore:
    "ہمارے ریکارڈ سے پتہ چلتا ہے کہ آپ پہلے ہی یہ سروے مکمل کر چکے ہیں۔",
  loadingSurvey: "...سروے لوڈ کر رہا ہے",
  optionsCaption: "...منتخب کریں ",
  value: "value",
  requiredError: "براہ کرم سوال کا جواب دیں۔",
  requiredErrorInPanel: "براہ کرم کم از کم ایک سوال کا جواب دیں۔",
  requiredInAllRowsError: "براہ کرم تمام قطاروں میں سوالات کے جوابات دیں۔",
  numericError: "اس کا جواب عدد میں ہونا چاہئے۔",
  minError: "عدد صفر سے کم نہیں ہونی چاہئے",
  maxError: "عدد صفر سے زیادہ نہیں ہونی چاہیے",
  textMinLength: "براہ کرم کم از کم صفر حروف درج کریں۔",
  textMaxLength: "براہ کرم صفر سے زیادہ حروف درج نہ کریں۔",
  textMinMaxLength: "براہ کرم کم از کم صفر اور ایک سے زیادہ حروف درج کریں۔",
  minRowCountError: "براہ کرم کم از کم صفر صفیں بھریں۔",
  minSelectError: "براہ کرم کم از کم صفر مختلف حالتیں منتخب کریں۔",
  maxSelectError: "براہ کرم صفر سے زیادہ متغیرات منتخب نہ کریں۔",
  numericMinMax: "صفر' کم از کم ایک اور زیادہ سے زیادہ دو ہونا چاہیے'",
  numericMin: "صفر' کم از کم ایک ہونا چاہیے'",
  numericMax: "صفر زیادہ سے زیادہ ایک ہونا چاہیے",
  invalidEmail: "برائے مہربانی درست ای میل ایڈریس لکھیں",
  invalidExpression: " کلام: {0} کو 'درست' لوٹنا چاہیے۔",
  urlRequestError: "درخواست نے غلطی '{0}' لوٹائی۔ {1}",
  urlGetChoicesError:
    "درخواست نے خالی ڈیٹا واپس کر دیا۔ یا 'راستہ' پراپرٹی غلط ہے۔",
  exceedMaxSize: "فائل کا سائز {0} سے زیادہ نہیں ہونا چاہیے.",
  otherRequiredError: "براہ کرم دوسری عدد درج کریں۔ ",
  uploadingFile:
    "آپ کی فائل اپ لوڈ ہو رہی ہے۔ براہ کرم چند سیکنڈ انتظار کریں اور دوبارہ کوشش کریں۔",
  loadingFile: "..لوڈ ہو رہا ہے۔",
  chooseFile: "..فائلیں منتخب کریں۔ ",
  noFileChosen: "کوئی فائل منتخب نہیں کی گئی ",
  fileDragAreaPlaceholder:
    "یہاں فائل ڈراپ کریں یا فائل کو لوڈ کرنے کے لیے نیچے والے بٹن پر کلک کریں۔",
  confirmDelete: "کیا آپ ریکارڈ حذف کرنا چاہتے ہیں؟",
  keyDuplicationError: "یہ عدد منفرد ہونی چاہیے۔",
  addColumn: "کالم شامل کریں۔",
  addRow: "قطار شامل کریں۔",
  removeRow: "مٹائے",
  emptyRowsText: "کوئی قطار نہیں ہیں۔ ",
  addPanel: "نیا شامل کریں",
  removePanel: "مٹائے",
  choices_Item: "آئٹم",
  matrix_column: "کالم۔",
  matrix_row: "قطار۔",
  multipletext_itemname: "عبارت",
  savingData: "...نتائج کو سرور پر محفوظ کیا جا رہا ہے",
  savingDataError: "ایک خرابی پیش آگئی اور ہم نتائج کو محفوظ نہیں کر سکے۔",
  savingDataSuccess: "نتائج کامیابی سے محفوظ ہو گئے۔",
  saveAgainButton: "دوبارہ کوشش کریں",
  timerMin: "منٹ",
  timerSec: "سیکنڈ",
  timerSpentAll: "آپ نے اس صفحے پر {0} اور مجموعی طور پر {1} خرچ کیا ہے۔",
  timerSpentPage: "آپ نے اس صفحے پر {0} خرچ کیا ہے۔",
  timerSpentSurvey: "آپ نے مجموعی طور پر {0} خرچ کیا ہے۔",
  timerLimitAll:
    "آپ نے اس صفحے پر {0} میں سے {1} اور مجموعی طور پر {2} میں سے {3} خرچ کیے ہیں۔",
  timerLimitPage: "آپ نے اس صفحے پر {0} میں سے {0} خرچ کیا ہے۔",
  timerLimitSurvey: "آپ نے کل {1} میں سے {1} خرچ کیا ہے۔",
  cleanCaption: "صاف",
  clearCaption: "صاف",
  signaturePlaceHolder: "یہاں سائن کریں۔",
  chooseFileCaption: "فائل منتخب کریں",
  removeFileCaption: "اس فائل کو ہٹائے۔",
  booleanCheckedLabel: "جی ہاں",
  booleanUncheckedLabel: "نہیں",
  confirmRemoveFile: "کیا آپ واقعی اس فائل کو ہٹانا چاہتے ہیں: {0}؟",
  confirmRemoveAllFiles: "کیا آپ تمام فائلیں ہٹانا چاہتے ہیں؟",
  questionTitlePatternText: "سوال کا عنوان۔",
  modalCancelButtonText: "منسوخ کریں",
  modalApplyButtonText: "درخواست دیں",
};

//Uncomment these two lines on creating a translation file. You should replace "en" and enStrings with your locale ("fr", "de" and so on) and your variable.
surveyLocalization.locales["ur"] = urduSurveyStrings;
surveyLocalization.localeNames["ur"] = "Urdu";
