resources:
  repositories:
    - repository: azurepipelines
      type: github
      endpoint: surveyjs
      name: surveyjs/azure-pipelines

trigger: none
pr: none

extends:
  template: library.yml@azurepipelines