resources:
  repositories:
    - repository: azurepipelines
      type: github
      endpoint: surveyjs
      name: surveyjs/azure-pipelines
      ref: theme-adapters-pipeline

trigger: none
pr: none

extends:
  template: library.yml@azurepipelines
