resources:
  repositories:
    - repository: azurepipelines
      type: github
      endpoint: surveyjs
      name: surveyjs/azure-pipelines

trigger: none
pr: none

pool:
  name: main-selfhosted
      
extends:
  template: library.yml@azurepipelines